import {backupAll} from '@/lib/backup';
import {AppError} from '@/lib/workspace';
import {env} from 'cloudflare:workers';
import {authorizedStore} from '@/lib/auth';
import {json,failure,spaceOf,body} from '@/lib/http';
import {sha256} from '@/lib/protocol';
export async function GET(request:Request){try{const {store}=await authorizedStore(request),u=new URL(request.url),space=spaceOf(u.searchParams.get('space')||'personal'),id=u.searchParams.get('id');if(id){const row=await store.q("SELECT sha256,status FROM backup_runs WHERE owner_id=? AND space=? AND id=?",store.owner,space,id).first<{sha256:string;status:string}>();if(!row||row.status!=='success')return json({error:'备份尚不可用'},404);const data=await env.BACKUPS.get(store.owner+'/'+space+'/'+id+'/'+row.sha256,'json') as {sha256:string;workspace:unknown}|null;if(!data)return json({error:'备份正在传播，请稍后重试'},503);if(await sha256(data.workspace)!==data.sha256)return json({error:'备份校验失败'},500);return json(data);}const total=await store.q("SELECT COALESCE(SUM(bytes),0) size FROM backup_runs WHERE status='success'").first<{size:number}>();return json((await store.q('SELECT id,status,bytes,sha256,error,created_at FROM backup_runs WHERE owner_id=? AND space=? ORDER BY created_at DESC LIMIT 100',store.owner,space).all()).results.map(row=>({...row,capacityWarning:(total?.size||0)>=384*1024*1024})));}catch(e){return failure(e);}}

export async function POST(request:Request){try{const {store}=await authorizedStore(request);const input=await body(request);if(input.confirm!==true)throw new AppError('请明确确认创建云端备份');const id='manual-'+new Date().toISOString().replaceAll(':','-')+'-'+crypto.randomUUID();await backupAll(env.DB,env.BACKUPS,{ownerId:store.owner,id});const rows=(await store.q('SELECT space,id,status,error,sha256,bytes,created_at FROM backup_runs WHERE owner_id=? AND id=?',store.owner,id).all()).results;const ok=rows.length===2&&rows.every(r=>r.status==='success');return json({ok,id,backups:rows},ok?200:503);}catch(e){return failure(e);}}
