import test from 'node:test';
import assert from 'node:assert/strict';
import 'fake-indexeddb/auto';
import {SyncEngine} from '../lib/client-sync.ts';
import {database} from './d1-helper.ts';
import {Store} from '../lib/storage-v2.ts';
import {enableCoordination} from '../lib/coordinated-store.ts';
import {newTask} from '../lib/domain.ts';
import {AppError} from '../lib/workspace.ts';
import {ConflictError,type Operation} from '../lib/protocol.ts';
Object.defineProperty(globalThis,'document',{value:{hidden:false},configurable:true});
const category={id:'cat-study',flow:'study',name:'考试',displayLabel:'考试',color:'#ef4444',archived:false};
async function fixture(){const {db,sqlite}=database(),store=new Store(db,crypto.randomUUID());await store.initialize('synthetic');await enableCoordination(store,'personal',0);let offline=false;const requests:Operation[]=[];
 globalThis.fetch=async(path,init)=>{if(offline)throw new TypeError('offline');const url=typeof path==='string'?path:path instanceof URL?path.href:path.url;try{if(url.includes('/session'))return Response.json({owner:store.owner,loginId:'synthetic',local:true,email:'synthetic',expiresAt:Date.now()+86400000,serverTime:new Date().toISOString()});if(url.includes('/sync'))return Response.json({...await store.sync('personal',null),owner:store.owner});assert.equal(typeof init?.body,'string');const input=JSON.parse(init!.body as string);requests.push(input.operation);return Response.json(await store.mutate(input));}catch(e){return Response.json({error:e instanceof Error?e.message:'error',...(e instanceof ConflictError?{code:e.code,latest:e.latest,latestSettings:e.latestSettings,settingsVersion:e.settingsVersion}:{})},{status:e instanceof AppError?e.status:500});}};
 const engine=new SyncEngine();await engine.start(()=>{});return {store,engine,sqlite,requests,offline:(v:boolean)=>offline=v};}
void test('ready workspace: offline category then task replays without touching queue until task creation',async(t)=>{const f=await fixture();t.after(()=>{f.engine.stop();f.sqlite.close();});const before=await f.store.snapshot('personal');f.offline(true);await f.engine.enqueue({kind:'categoryCreate',category});await f.engine.enqueue({kind:'save',task:{...newTask(),title:'合成离线关联',categoryId:category.id,coordOrder:1}});f.offline(false);await f.engine.sync();assert.equal(f.engine.queue.length,0,JSON.stringify(f.engine.queue));assert.equal(f.requests[0].kind,'categoryCreate');const after=await f.store.snapshot('personal');assert.equal(after.workspace.tasks[0].categoryId,category.id);assert.equal(after.workspace.tasks[0].coordOrder,1);assert.equal(after.workspace.queueVersion,(before.workspace.queueVersion||0)+1);});
void test('ready workspace: category rename and density preserve task versions and queue version',async(t)=>{const f=await fixture();t.after(()=>{f.engine.stop();f.sqlite.close();});await f.engine.enqueue({kind:'categoryCreate',category});await f.engine.enqueue({kind:'save',task:{...newTask(),title:'合成引用',categoryId:category.id,coordOrder:1}});const before=await f.store.snapshot('personal');await f.engine.enqueue({kind:'categoryUpdate',categoryId:category.id,patch:{name:'期末考',color:'#001122'}});await f.engine.enqueue({kind:'settings',density:'comfortable'});const after=await f.store.snapshot('personal');assert.equal(f.engine.queue.length,0,JSON.stringify(f.engine.queue));assert.deepEqual(after.workspace.tasks,before.workspace.tasks);assert.equal(after.workspace.queueVersion,before.workspace.queueVersion);assert.equal(after.workspace.settings.categories![0].name,'期末考');});
void test('ready workspace: choose cloud on category conflict unblocks a queued referencing task',async(t)=>{const f=await fixture();t.after(()=>{f.engine.stop();f.sqlite.close();});await f.engine.enqueue({kind:'categoryCreate',category});f.offline(true);await f.engine.enqueue({kind:'categoryUpdate',categoryId:category.id,patch:{name:'本机名'}});await f.engine.enqueue({kind:'save',task:{...newTask(),title:'等待分类选择',categoryId:category.id}});const current=await f.store.snapshot('personal');await f.store.mutate({space:'personal',clientId:'remote',operationId:crypto.randomUUID(),baseVersion:current.settingsVersion,operation:{kind:'categoryUpdate',categoryId:category.id,patch:{name:'云端名'}}});f.offline(false);await f.engine.sync();const conflict=f.engine.queue.find(q=>q.categoryLocal)!;assert.equal(conflict.state,'conflict');await f.engine.resolveCategory(conflict.mutation.operationId,{name:'remote'});assert.equal(f.engine.queue.length,0,JSON.stringify(f.engine.queue));const after=await f.store.snapshot('personal');assert.equal(after.workspace.settings.categories![0].name,'云端名');assert.equal(after.workspace.tasks[0].categoryId,category.id);});
