import test from 'node:test';
import assert from 'node:assert/strict';
import {Store} from '../lib/storage-v2.ts';
import {newTask} from '../lib/domain.ts';
import {enableCoordination} from '../lib/coordinated-store.ts';
import {categoryPresets,ensureCategoryPresets} from '../lib/categories.ts';
import {validateImport} from '../lib/workspace.ts';
import {sha256} from '../lib/protocol.ts';
import {database} from './d1-helper.ts';
const category={id:'category-test',flow:'study',name:'考试',displayLabel:'考试',color:'#112233',archived:false};
async function fixture(){const {db,sqlite}=database(),store=new Store(db,'synthetic-integrity');await store.initialize('synthetic');async function write(operation:unknown,taskId?:string){const s=await store.snapshot('personal');return store.mutate({space:'personal',clientId:'integrity',operationId:crypto.randomUUID(),baseVersion:taskId?s.workspace.tasks.find(t=>t.id===taskId)?.version||0:s.settingsVersion,taskId,protocolVersion:3,queueVersion:s.workspace.queueVersion,capturedAt:new Date().toISOString(),operation});}return {store,sqlite,write};}
void test('presets are idempotent, preserve edited stable IDs, and leave unrelated flows empty',()=>{const edited=categoryPresets().map(c=>c.id==='category-preset-study-1'?{...c,name:'修改考试',archived:true}:c);assert.deepEqual(ensureCategoryPresets(edited,'study'),edited);assert.deepEqual(ensureCategoryPresets(undefined,'projects'),[]);assert.equal(new Set(categoryPresets().map(c=>c.id)).size,8);});
void test('directory duplicate and capacity rejection leave the database readable and atomic',async()=>{const f=await fixture();await f.write({kind:'categoryCreate',category});const before=await f.store.snapshot('personal');await assert.rejects(()=>f.write({kind:'categoryCreate',category:{...category,id:'duplicate-name'}}));assert.deepEqual(await f.store.snapshot('personal'),before);const cats=Array.from({length:200},(_,i)=>({...category,id:'cap-'+i,name:'分类'+i,displayLabel:'分类'}));f.sqlite.prepare('UPDATE workspace_settings SET payload=? WHERE owner_id=? AND space=?').run(JSON.stringify({density:'compact',categories:cats}),f.store.owner,'personal');const capped=await f.store.snapshot('personal');await assert.rejects(()=>f.write({kind:'categoryCreate',category:{...category,id:'overflow'}}));assert.deepEqual(await f.store.snapshot('personal'),capped);});
void test('ready task mutations preserve archived references but reject new, wrong-flow and other-space references',async()=>{const f=await fixture();await f.write({kind:'categoryCreate',category});await enableCoordination(f.store,'personal',1);const task={...newTask('study'),id:'existing',title:'原引用',categoryId:category.id};await f.write({kind:'create',task},task.id);await f.write({kind:'categoryUpdate',categoryId:category.id,patch:{archived:true}});await f.write({kind:'patch',patch:{title:'旧客户端未传分类'}},task.id);assert.equal((await f.store.snapshot('personal')).workspace.tasks[0].categoryId,category.id);await assert.rejects(()=>f.write({kind:'create',task:{...task,id:'copy'}},'copy'));await assert.rejects(()=>f.write({kind:'patch',patch:{flow:'research',categoryId:category.id}},task.id));await f.write({kind:'patch',patch:{flow:'research'}},task.id);assert.ok(!(await f.store.snapshot('personal')).workspace.tasks[0].categoryId);await assert.rejects(()=>f.store.mutate({space:'demo',clientId:'integrity',operationId:crypto.randomUUID(),baseVersion:0,taskId:'other-space',operation:{kind:'create',task:{...task,id:'other-space'}}}));assert.equal((await f.store.snapshot('demo')).workspace.tasks.length,0);});
void test('old backup hashes are unchanged and preview/restore retain the current directory with exact notice',async()=>{const f=await fixture();const old={schemaVersion:1 as const,space:'personal' as const,revision:0,tasks:[{...newTask('study'),id:'old',title:'旧备份'}],settings:{density:'compact' as const}};assert.equal(await sha256(validateImport(old)),await sha256(old));assert.equal(Object.hasOwn(validateImport(old).settings,'categories'),false);await f.write({kind:'categoryCreate',category});const preview=await f.store.preview('personal',old,'restore');assert.equal(preview.categoryNotice,'恢复卡片无分类，现有分类目录保留');await f.store.importWorkspace('personal',old,'old-backup',preview.sourceHash,preview.expectedRevision,'restore');const after=await f.store.snapshot('personal');assert.deepEqual(after.workspace.settings.categories,[category]);assert.ok(!after.workspace.tasks[0].categoryId);});
