import test from 'node:test';
import assert from 'node:assert/strict';
import 'fake-indexeddb/auto';
import {SyncEngine} from '../lib/client-sync.ts';
import {newTask} from '../lib/domain.ts';
import type {Category} from '../lib/categories.ts';
import type {Workspace} from '../lib/workspace.ts';
import {applyTaskMutation,type Mutation,type Receipt} from '../lib/protocol.ts';
Object.defineProperty(globalThis,'document',{value:{hidden:false},configurable:true});
const category=(id='cat-a'):Category=>({id,flow:'study',name:'考试',displayLabel:'考试',color:'#DC2626',archived:false});
function fixture(){let offline=false,lost=false,expired=false,version=0,race=false,partial=false;const owner=crypto.randomUUID(),requests:Mutation[]=[],receipts=new Map();const w:Workspace={schemaVersion:1,space:'personal',revision:0,tasks:[],settings:{density:'compact',categories:[category()]}};
 globalThis.fetch=async(path,init)=>{const url=typeof path==='string'?path:path instanceof URL?path.href:path.url;if(offline)throw new TypeError('offline');if(expired)return Response.json({error:'expired'},{status:401});if(url.includes('/session'))return Response.json({owner,email:'synthetic',local:true,expiresAt:Date.now()+86400000,serverTime:new Date().toISOString()});if(url.includes('/sync'))return Response.json(partial?{owner,mode:'delta',changes:[{seq:w.revision,kind:'settings',dto:{settings:{density:w.settings.density}}}],nextCursor:w.revision,settingsVersion:version,hasMore:false,serverTime:new Date().toISOString()}:{owner,mode:'snapshot',workspace:w,nextCursor:w.revision,settingsVersion:version,hasMore:false,serverTime:new Date().toISOString()});const m:Mutation=JSON.parse(init?.body as string);requests.push(m);if(receipts.has(m.operationId))return Response.json(receipts.get(m.operationId));const op=m.operation;let result:Partial<Receipt>;if(race){race=false;version++;w.revision++;w.settings.categories![0].displayLabel='云端';}
 if(op.kind==='categoryCreate'||op.kind==='categoryUpdate'||op.kind==='settings'){if(m.baseVersion!==version)return Response.json({error:'settings conflict',latestSettings:w.settings,settingsVersion:version},{status:409});if(op.kind==='categoryCreate')w.settings.categories!.push(op.category);else if(op.kind==='categoryUpdate'){const c=w.settings.categories!.find(c=>c.id===op.categoryId)!;Object.assign(c,op.patch);}else w.settings.density=op.density;version++;result={settings:partial?{density:w.settings.density}:structuredClone(w.settings),settingsVersion:version};}
 else {const old=w.tasks.find(t=>t.id===m.taskId)||null;const task=applyTaskMutation(old,m);if(task.categoryId)assert.ok(w.settings.categories!.some(c=>c.id===task.categoryId),'directory must sync first');w.tasks=w.tasks.filter(t=>t.id!==task.id).concat(task);result={task};}
 w.revision++;result={...result,cursor:w.revision,operationId:m.operationId,serverTime:new Date().toISOString()};receipts.set(m.operationId,result);if(lost){lost=false;throw new TypeError('lost response');}return Response.json(result);};
 return {w,requests,offline:(x:boolean)=>offline=x,lost:()=>lost=true,expire:()=>expired=true,race:()=>race=true,partial:()=>partial=true,remote:(id:string,patch:Partial<Category>)=>{Object.assign(w.settings.categories!.find(c=>c.id===id)!,patch);version++;w.revision++;}};
}
void test('offline category creation, density overlay and referencing draft survive restart; directory ACK precedes task',async(t)=>{const f=fixture(),a=new SyncEngine();t.after(()=>a.stop());await a.start(()=>{});f.offline(true);const c={...category('new'),name:'作业',displayLabel:'作业'};await a.enqueue({kind:'categoryCreate',category:c});await a.enqueue({kind:'settings',density:'comfortable'});assert.equal(a.display()!.settings.categories!.length,2);const task={...newTask('study'),title:'合成分类任务',categoryId:c.id};await a.saveDraft(task,task);await a.enqueue({kind:'save',task});a.stop();const b=new SyncEngine();await b.start(()=>{});assert.equal((await b.drafts())[0].draft.categoryId,c.id);f.offline(false);await b.sync();assert.equal(f.w.tasks[0].categoryId,c.id);assert.equal(b.queue.length,0);assert.equal(f.w.settings.density,'comfortable');assert.equal(f.requests[0].operation.kind,'categoryCreate');assert.equal(b.display()!.settings.categories!.length,2);b.stop();});
void test('different category IDs and different fields merge; same field exposes both and resolves explicitly',async()=>{const f=fixture();f.w.settings.categories!.push({...category('cat-b'),name:'作业',displayLabel:'作业'});const a=new SyncEngine();await a.start(()=>{});f.offline(true);await a.enqueue({kind:'categoryUpdate',categoryId:'cat-a',patch:{color:'#000000'}});f.remote('cat-b',{color:'#FFFFFF'});f.remote('cat-a',{name:'测验'});f.offline(false);await a.sync();assert.equal(a.queue.length,0);assert.equal(f.w.settings.categories![0].name,'测验');assert.equal(f.w.settings.categories![0].color,'#000000');assert.equal(f.w.settings.categories![1].color,'#FFFFFF');f.offline(true);await a.enqueue({kind:'categoryUpdate',categoryId:'cat-a',patch:{name:'本机名'}});f.remote('cat-a',{name:'云端名'});f.offline(false);await a.sync();const q=a.queue[0];assert.equal(q.state,'conflict');assert.deepEqual(q.categoryConflicts,['name']);assert.equal(q.categoryLocal!.name,'本机名');assert.equal(q.categoryLatest!.name,'云端名');await a.resolveCategory(q.mutation.operationId,{name:'remote'});assert.equal(a.queue.length,0);assert.equal(f.w.settings.categories![0].name,'云端名');a.stop();});
void test('lost category ACK retries identical mutation; authentication expiry retains category queue',async(t)=>{const f=fixture(),a=new SyncEngine();t.after(()=>a.stop());await a.start(()=>{});f.lost();await a.enqueue({kind:'categoryUpdate',categoryId:'cat-a',patch:{color:'#123456'}});const original=JSON.parse(JSON.stringify(a.queue[0].mutation));await a.sync();assert.equal(a.queue.length,0);assert.deepEqual(f.requests[0],original);assert.deepEqual(f.requests[1],original);f.offline(true);await a.enqueue({kind:'categoryUpdate',categoryId:'cat-a',patch:{archived:true}});f.offline(false);f.expire();await a.sync();assert.equal(a.display(),null);assert.equal(a.queue.length,1);a.stop();});
void test('category conflict blocks referencing task while independent category still synchronizes',async(t)=>{const f=fixture(),a=new SyncEngine();t.after(()=>a.stop());await a.start(()=>{});f.offline(true);await a.enqueue({kind:'categoryUpdate',categoryId:'cat-a',patch:{color:'#000000'}});await a.enqueue({kind:'save',task:{...newTask('study'),title:'等待分类',categoryId:'cat-a'}});await a.enqueue({kind:'categoryCreate',category:{...category('cat-b'),name:'作业',displayLabel:'作业'}});f.remote('cat-a',{color:'#FFFFFF'});f.offline(false);await a.sync();assert.equal(f.w.tasks.length,0);assert.ok(f.w.settings.categories!.some(c=>c.id==='cat-b'));assert.equal(a.queue.length,2);a.stop();});


void test('settings CAS race retires rejected ID and rebases category without overwriting remote fields',async(t)=>{const f=fixture(),a=new SyncEngine();t.after(()=>a.stop());await a.start(()=>{});f.race();await a.enqueue({kind:'categoryUpdate',categoryId:'cat-a',patch:{color:'#010203'}});assert.equal(a.queue.length,1);const rejected=f.requests[0].operationId;assert.notEqual(a.queue[0].mutation.operationId,rejected);await a.sync();assert.equal(a.queue.length,0);assert.equal(f.w.settings.categories![0].displayLabel,'云端');assert.equal(f.w.settings.categories![0].color,'#010203');});
void test('sequential offline edits to same category retain order and merged values',async(t)=>{const f=fixture(),a=new SyncEngine();t.after(()=>a.stop());await a.start(()=>{});f.offline(true);await a.enqueue({kind:'categoryUpdate',categoryId:'cat-a',patch:{name:'期末考'}});await a.enqueue({kind:'categoryUpdate',categoryId:'cat-a',patch:{name:'期中考',color:'#010203'}});f.offline(false);await a.sync();assert.equal(a.queue.length,0);assert.equal(f.w.settings.categories![0].name,'期中考');assert.equal(f.w.settings.categories![0].color,'#010203');});


void test('density-only ACK and delta preserve the cached directory and task references',async(t)=>{const f=fixture(),a=new SyncEngine();t.after(()=>a.stop());await a.start(()=>{});f.partial();await a.enqueue({kind:'settings',density:'comfortable'});assert.equal(a.queue.length,0);assert.equal(a.display()!.settings.density,'comfortable');assert.equal(a.display()!.settings.categories![0].id,'cat-a');await a.sync();assert.equal(a.display()!.settings.categories![0].id,'cat-a');});
void test('remote changes after conflict presentation are not silently overwritten by resolution',async(t)=>{const f=fixture(),a=new SyncEngine();t.after(()=>a.stop());await a.start(()=>{});f.offline(true);await a.enqueue({kind:'categoryUpdate',categoryId:'cat-a',patch:{name:'本机名'}});f.remote('cat-a',{name:'云端一'});f.offline(false);await a.sync();const id=a.queue[0].mutation.operationId;f.remote('cat-a',{name:'云端二'});await a.sync();await a.resolveCategory(id,{name:'local'});assert.equal(f.w.settings.categories![0].name,'云端二');assert.equal(a.queue[0].state,'conflict');assert.equal(a.queue[0].categoryLatest!.name,'云端二');});
