import test from 'node:test';
import assert from 'node:assert/strict';
import 'fake-indexeddb/auto';
import {SyncEngine,type EngineState} from '../lib/client-sync.ts';
import {localPut} from '../lib/device-db.ts';
import {newTask,type Task} from '../lib/domain.ts';
import {applyTaskMutation,type Mutation} from '../lib/protocol.ts';
Object.defineProperty(globalThis,'document',{value:{hidden:false}});
function fixture(){let loginId=crypto.randomUUID(),offline=false,lost=false,expired=false,w={schemaVersion:1 as const,space:'personal' as const,revision:0,tasks:[] as Task[],settings:{density:'compact' as const}};const receipts=new Map(),requests:Mutation[]=[];const owner=crypto.randomUUID();globalThis.fetch=async(path:any,init?:RequestInit)=>{if(offline)throw new TypeError('offline');if(expired)return Response.json({error:'expired'},{status:401});if(String(path)==='/logout')return Response.json({ok:true});if(String(path).includes('/session'))return Response.json({owner,loginId,email:'synthetic',local:true,expiresAt:Date.now()+86400000,serverTime:new Date().toISOString()});if(String(path).includes('/sync'))return Response.json({owner,mode:'snapshot',workspace:w,nextCursor:w.revision,settingsVersion:0,hasMore:false,serverTime:new Date().toISOString()});const m=JSON.parse(String(init?.body));requests.push(m);if(receipts.has(m.operationId))return Response.json(receipts.get(m.operationId));const old=w.tasks.find(t=>t.id===m.taskId)||null;if(old&&old.version!==m.baseVersion)return Response.json({error:'conflict',latest:old},{status:409});const task=applyTaskMutation(old,m);w.tasks=w.tasks.filter(t=>t.id!==task.id).concat(task);w.revision++;const result={task,cursor:w.revision,operationId:m.operationId,serverTime:new Date().toISOString()};receipts.set(m.operationId,result);if(lost){lost=false;throw new TypeError('response lost');}return Response.json(result);};return {w,requests,owner,newLogin:()=>loginId=crypto.randomUUID(),setOffline:(v:boolean)=>offline=v,setLost:()=>lost=true,setExpired:()=>expired=true};}
test('offline create and draft survive engine restart; operation cleared only after ACK',async()=>{const f=fixture(),a=new SyncEngine();await a.start(()=>{});const task={...newTask(),title:'离线新卡'};f.setOffline(true);await a.saveDraft(task,{...task,notes:'关闭前草稿'});await a.enqueue({kind:'save',task});assert.equal(a.queue.length,1);const id=a.queue[0].mutation.operationId;a.stop();const b=new SyncEngine();await b.start(()=>{});assert.equal(b.queue[0].mutation.operationId,id);assert.equal((await b.drafts())[0].draft.notes,'关闭前草稿');f.setOffline(false);await b.sync();assert.equal(b.queue.length,0);assert.equal(f.w.tasks[0].title,'离线新卡');b.stop();});
test('lost response retries immutable operation ID after restart without duplicate task',async()=>{const f=fixture(),a=new SyncEngine();await a.start(()=>{});f.setLost();await a.enqueue({kind:'save',task:{...newTask(),title:'响应丢失'}});assert.equal(a.queue.length,1);const original=structuredClone(a.queue[0].mutation);a.stop();const b=new SyncEngine();await b.start(()=>{});assert.equal(b.queue.length,0);assert.equal(f.w.tasks.length,1);assert.deepEqual(f.requests[0],original);assert.deepEqual(f.requests[1],original);b.stop();});
test('expired identity hides workspace and preserves outbox plus drafts',async()=>{const f=fixture(),a=new SyncEngine();let state:EngineState;await a.start(s=>state=s);const task={...newTask(),title:'私有草稿'};f.setOffline(true);await a.saveDraft(task,task);await a.enqueue({kind:'save',task});f.setOffline(false);f.setExpired();await a.sync();assert.equal(state!.workspace,null);assert.equal(a.queue.length,1);assert.equal((await a.drafts()).length,1);await assert.rejects(()=>a.enqueue({kind:'save',task}));a.stop();});
test('different field rebase keeps remote edits; same field remains conflict',async()=>{const f=fixture(),a=new SyncEngine();await a.start(()=>{});await a.enqueue({kind:'save',task:{...newTask(),title:'原名'}});const base=structuredClone(f.w.tasks[0]);f.setOffline(true);await a.enqueue({kind:'save',task:{...base,title:'本机名'}},base);f.w.tasks[0]={...base,notes:'远端备注',version:base.version+1};f.w.revision++;f.setOffline(false);await a.sync();assert.equal(f.w.tasks[0].notes,'远端备注');assert.equal(f.w.tasks[0].title,'本机名');const next=structuredClone(f.w.tasks[0]);f.setOffline(true);await a.enqueue({kind:'save',task:{...next,title:'本机冲突'}},next);f.w.tasks[0]={...next,title:'远端冲突',version:next.version+1};f.w.revision++;f.setOffline(false);await a.sync();assert.equal(a.queue[0].state,'conflict');assert.equal(f.w.tasks[0].title,'远端冲突');a.stop();});
test('sequential offline edits replay in order and quick-action conflict can be confirmed',async()=>{const f=fixture(),a=new SyncEngine();await a.start(()=>{});await a.enqueue({kind:'save',task:{...newTask(),title:'起点'}});f.setOffline(true);let base=a.display()!.tasks[0];await a.enqueue({kind:'save',task:{...base,title:'第一步'}},base);base=a.display()!.tasks[0];await a.enqueue({kind:'save',task:{...base,title:'第二步'}},base);f.setOffline(false);await a.sync();assert.equal(a.queue.length,0);assert.equal(f.w.tasks[0].title,'第二步');f.setOffline(true);await a.enqueue({kind:'flag',id:f.w.tasks[0].id});f.w.tasks[0]={...f.w.tasks[0],notes:'其他设备编辑',version:f.w.tasks[0].version+1};f.w.revision++;f.setOffline(false);await a.sync();assert.equal(a.queue[0].state,'conflict');await a.resolve(a.queue[0].mutation.operationId,{});assert.equal(f.w.tasks[0].flagged,true);assert.equal(f.w.tasks[0].notes,'其他设备编辑');a.stop();});

test('offline logout locks immediately, survives reload and resumes only after new login',async()=>{const f=fixture(),a=new SyncEngine();let state:EngineState;await a.start(s=>state=s);f.setOffline(true);const task={...newTask(),title:'退出仍保留草稿'};await a.saveDraft(task,task);await a.enqueue({kind:'save',task});await a.logout();assert.equal(state!.workspace,null);assert.equal(state!.queue.length,0);const b=new SyncEngine();await b.start(s=>state=s);assert.equal(state!.workspace,null);f.setOffline(false);await b.connect();assert.equal(state!.workspace,null);assert.equal(f.requests.length,0);f.newLogin();await b.connect();assert.equal(f.w.tasks.length,1);assert.equal((await b.drafts()).length,1);b.stop();});
