import test from 'node:test';
import assert from 'node:assert/strict';
import 'fake-indexeddb/auto';
import {SyncEngine} from '../lib/client-sync.ts';
import {database} from './d1-helper.ts';
import {Store} from '../lib/storage-v2.ts';
import {enableCoordination} from '../lib/coordinated-store.ts';
import {newTask} from '../lib/domain.ts';
Object.defineProperty(globalThis,'document',{value:{hidden:false}});
async function fixture(){const {db}=database(),store=new Store(db,crypto.randomUUID());await store.initialize('synthetic');await enableCoordination(store,'personal',0);let offline=false;
 globalThis.fetch=async(path:any,init?:RequestInit)=>{if(offline)throw new TypeError('offline');try{if(String(path).includes('/session'))return Response.json({owner:store.owner,loginId:crypto.randomUUID(),local:true,email:'synthetic',expiresAt:Date.now()+86400000,serverTime:new Date().toISOString()});if(String(path).includes('/sync'))return Response.json({...await store.sync('personal',null),owner:store.owner});return Response.json(await store.mutate(JSON.parse(String(init?.body))));}catch(e){return Response.json({error:(e as Error).message,code:(e as any).code,...('latest' in (e as any)?{latest:(e as any).latest}:{})},{status:(e as any).status||500});}};
 const engine=new SyncEngine();await engine.start(()=>{});return {store,engine,offline:(v:boolean)=>offline=v};}
test('coordinated offline sequential completions predict all affected versions and replay without self-conflicts',async()=>{const f=await fixture();try{const ids=[];for(let i=1;i<=4;i++){const task={...newTask(),title:'offline fixture',coordOrder:i};ids.push(task.id);await f.engine.enqueue({kind:'save',task});}f.offline(true);await f.engine.enqueue({kind:'complete',id:ids[0]});await f.engine.enqueue({kind:'complete',id:ids[2]});assert.deepEqual(f.engine.display()!.tasks.map(t=>t.coordOrder),[null,1,null,2]);assert.equal(f.engine.queue.length,2);f.offline(false);await f.engine.sync();assert.equal(f.engine.queue.length,0,JSON.stringify(f.engine.queue));assert.deepEqual((await f.store.snapshot('personal')).workspace.tasks.map(t=>t.coordOrder),[null,1,null,2]);}finally{f.engine.stop();}});
test('other device queue change preserves offline operation until explicit re-execution',async()=>{const f=await fixture();try{for(let i=1;i<=2;i++)await f.engine.enqueue({kind:'save',task:{...newTask(),title:'device fixture',coordOrder:i}});const w=f.engine.display()!,[a,b]=w.tasks;f.offline(true);await f.engine.enqueue({kind:'complete',id:b.id});await f.store.mutate({space:'personal',clientId:'second-device',operationId:crypto.randomUUID(),taskId:a.id,baseVersion:a.version,protocolVersion:3,queueVersion:w.queueVersion,operation:{kind:'setStatus',value:'已结束'}});f.offline(false);await f.engine.sync();assert.equal(f.engine.queue[0].queueConflict,true);assert.equal((await f.store.snapshot('personal')).workspace.tasks[1].coordOrder,1);await f.engine.resolveQueue(f.engine.queue[0].mutation.operationId);assert.equal(f.engine.queue.length,0);assert.equal((await f.store.snapshot('personal')).workspace.tasks[1].status,'已结束');}finally{f.engine.stop();}});
test('manual field conflict resolution emits the current coordination protocol',async()=>{const f=await fixture();try{await f.engine.enqueue({kind:'save',task:{...newTask(),title:'initial'}});const t=f.engine.display()!.tasks[0],w=f.engine.display()!;f.offline(true);await f.engine.enqueue({kind:'save',task:{...t,title:'local'}},t);await f.store.mutate({space:'personal',clientId:'second-device',operationId:crypto.randomUUID(),taskId:t.id,baseVersion:t.version,protocolVersion:3,queueVersion:w.queueVersion,operation:{kind:'patch',patch:{title:'remote'}}});f.offline(false);await f.engine.sync();assert.equal(f.engine.queue[0].state,'conflict');await f.engine.resolve(f.engine.queue[0].mutation.operationId,{title:'local'});assert.equal(f.engine.queue.length,0);assert.equal((await f.store.snapshot('personal')).workspace.tasks[0].title,'local');}finally{f.engine.stop();}});
