import test from 'node:test';
import assert from 'node:assert/strict';
import {setup,database} from './d1-helper.ts';
import {Store} from '../lib/storage-v2.ts';
import {newTask} from '../lib/domain.ts';
import {enableCoordination,coordinationPreview,readHistory} from '../lib/coordinated-store.ts';
import {aggregateAnalytics} from '../lib/analytics.ts';
import {sha256} from '../lib/protocol.ts';
const stamp=new Date().toISOString();
async function ready(){const c=await setup();await enableCoordination(c.store,'personal',0);return c;}
async function send(store:Store,operation:any,id?:string){const w=(await store.snapshot('personal')).workspace;const task=w.tasks.find(t=>t.id===id);const m={space:'personal' as const,clientId:'test-device',operationId:crypto.randomUUID(),taskId:id||operation.task?.id,baseVersion:task?.version||0,operation,protocolVersion:3,queueVersion:w.queueVersion,capturedAt:stamp};return {m,result:await store.mutate(m)};}
async function add(store:Store,n:number|null,daily=false,flow='study'){const task={...newTask(flow),title:'Synthetic task '+crypto.randomUUID(),coordOrder:n,daily};await send(store,{kind:'create',task},task.id);return task.id;}
async function tasks(store:Store){return (await store.snapshot('personal')).workspace.tasks;}
test('complete 3 atomically moves later cards and reports all affected rows',async()=>{const {store}=await ready();const ids=[];for(let n=1;n<=5;n++)ids.push(await add(store,n,n===5,'study'));const {result}=await send(store,{kind:'setStatus',value:'已结束'},ids[2]);const t=await tasks(store);assert.deepEqual(ids.map(id=>t.find(x=>x.id===id)!.coordOrder),[1,2,null,3,4]);assert.equal(result.tasks?.length,3);await send(store,{kind:'setStatus',value:'准备推进'},ids[2]);assert.deepEqual((await tasks(store)).map(t=>t.coordOrder),[1,2,3,4,5]);});
test('zeros are repeatable and completion leaves the positive queue unchanged',async()=>{const {store}=await ready();const a=await add(store,0),b=await add(store,0),c=await add(store,1);await send(store,{kind:'setStatus',value:'已结束'},a);const t=await tasks(store);assert.equal(t.find(x=>x.id===a)!.coordOrder,0);assert.equal(t.find(x=>x.id===b)!.coordOrder,0);assert.equal(t.find(x=>x.id===c)!.coordOrder,1);});
test('duplicate requests do not renumber or count completion twice',async()=>{const {store}=await ready();const id=await add(store,1);await add(store,2);const {m,result}=await send(store,{kind:'setStatus',value:'已结束'},id);assert.deepEqual(await store.mutate(m),result);assert.equal((await readHistory(store,'personal')).events.filter(e=>e.kind==='completed').length,1);});
test('stale device queue version rejects without changing any task or event',async()=>{const {store}=await ready();const a=await add(store,1),b=await add(store,2);const w=(await store.snapshot('personal')).workspace;await send(store,{kind:'setStatus',value:'已结束'},a);const before=await store.exportWorkspace('personal');await assert.rejects(()=>store.mutate({clientId:'stale',operationId:crypto.randomUUID(),space:'personal',taskId:b,baseVersion:w.tasks.find(t=>t.id===b)!.version,protocolVersion:3,queueVersion:w.queueVersion,operation:{kind:'setStatus',value:'已结束'}}),e=>(e as any).code==='QUEUE_VERSION_CONFLICT');assert.deepEqual(await store.exportWorkspace('personal'),before);});
test('old clients are rejected but existing receipts remain replayable',async()=>{const {store}=await ready();await assert.rejects(()=>store.mutate({clientId:'old',operationId:crypto.randomUUID(),space:'personal',taskId:'x',baseVersion:0,operation:{kind:'create',task:{...newTask(),id:'x',title:'legacy'}}}),e=>(e as any).status===426);});
test('daily completion releases order, undo withdraws the original day and restores position',async()=>{const {store}=await ready();const id=await add(store,1,true);await add(store,2);await send(store,{kind:'setCompleted',value:true,date:'2026-09-11',capturedAt:stamp},id);assert.equal((await tasks(store)).find(t=>t.id===id)!.coordOrder,null);await send(store,{kind:'setCompleted',value:false,date:'2026-09-11',capturedAt:stamp},id);assert.equal((await tasks(store)).find(t=>t.id===id)!.coordOrder,1);const h=await readHistory(store,'personal');assert.equal(aggregateAnalytics(h.events,{from:'2026-09-11',to:'2026-09-12',bucket:'day'},h.coverage).totals.completed,0);});
test('completion attribution survives flow edits and soft deletion',async()=>{const {store}=await ready();const id=await add(store,1);await send(store,{kind:'setStatus',value:'已结束'},id);await send(store,{kind:'patch',patch:{flow:'running'}},id);await send(store,{kind:'setDeleted',value:true},id);const h=await readHistory(store,'personal');assert.equal(h.events.find(e=>e.kind==='completed')!.flow,'study');assert.equal(h.events.filter(e=>e.kind==='created').length,1);});
test('pre-migration preview is read only and preserves original in backup',async()=>{const {store}=await setup();for(const n of [0,8,8,null]){const task={...newTask(),title:'legacy',coordOrder:n};await store.mutate({clientId:'old',operationId:crypto.randomUUID(),space:'personal',taskId:task.id,baseVersion:0,operation:{kind:'create',task}});}const before=await store.exportWorkspace('personal');const preview=await coordinationPreview(store,'personal');assert.deepEqual(await store.exportWorkspace('personal'),before);assert.equal(preview.changes.length,2);await enableCoordination(store,'personal',before.revision);assert.deepEqual((await tasks(store)).map(t=>t.coordOrder),[0,1,2,null]);const snapshot=await store.q('SELECT payload FROM snapshots_v2 WHERE owner_id=? AND space=?',store.owner,'personal').first<{payload:string}>();assert.deepEqual(JSON.parse(snapshot!.payload),before);});
test('history backup restores exactly without generating new creations or completions',async()=>{const {store}=await ready();const id=await add(store,1);await send(store,{kind:'setStatus',value:'已结束'},id);const backup=await store.exportWorkspace('personal');await send(store,{kind:'setStatus',value:'准备推进'},id);const p=await store.preview('personal',backup,'restore');await store.importWorkspace('personal',backup,'restore-history',await sha256(backup),p.expectedRevision,'restore');assert.deepEqual((await readHistory(store,'personal')).events,backup.history!.events);assert.equal((await tasks(store))[0].status,'已结束');});
test('owner and space history remain isolated',async()=>{const {store,db}=await ready();const other=new Store(db,'owner-b');await other.initialize('subject-b');await enableCoordination(other,'personal',0);await add(store,1);assert.equal((await readHistory(other,'personal')).events.length,0);assert.equal((await readHistory(store,'demo')).events.length,0);});
test('failure in the transaction leaves numbering and analytics unchanged',async()=>{const c=await ready();const id=await add(c.store,1);await add(c.store,2);const before=await c.store.exportWorkspace('personal');const original=c.db.batch.bind(c.db);c.db.batch=async(statements:any)=>{if(statements.some((s:any)=>String(s.sql).includes('INSERT INTO task_events')))throw new Error('injected failure');return original(statements);};await assert.rejects(()=>send(c.store,{kind:'setStatus',value:'已结束'},id));c.db.batch=original;assert.deepEqual(await c.store.exportWorkspace('personal'),before);});

test('restore invalidates pre-restore lost-response receipts and preserves the stale intent as conflict',async()=>{const {store}=await ready();const id=await add(store,1);const backup=await store.exportWorkspace('personal');const {m}=await send(store,{kind:'setStatus',value:'已结束'},id);const p=await store.preview('personal',backup,'restore');await store.importWorkspace('personal',backup,'restore-lost-response',p.sourceHash,p.expectedRevision,'restore');await assert.rejects(()=>store.mutate(m),e=>(e as any).code==='QUEUE_VERSION_CONFLICT');assert.equal((await tasks(store))[0].status,backup.tasks[0].status);});
