import test from 'node:test';import assert from 'node:assert/strict';
import {newTask} from '../lib/domain.ts';import {applyOperation,emptyWorkspace,validateTask,validateImport} from '../lib/workspace.ts';
const now=new Date('2026-09-10T15:59:00Z');
function fixture(daily=false){return applyOperation(emptyWorkspace('personal'),{kind:'save',task:{...newTask('research'),title:'竞赛组会',daily,notes:'保留备注',color:'#bc9bf5',coordLetter:'B',coordOrder:1}},now);}
test('create, update, version checks and stable ids',()=>{let w=fixture();const t=w.tasks[0];assert.equal(t.version,1);w=applyOperation(w,{kind:'save',task:{...t,title:'已改名'}},now);assert.equal(w.tasks[0].id,t.id);assert.equal(w.tasks[0].version,2);assert.throws(()=>applyOperation(w,{kind:'save',task:t}),/版本/);});
test('daily check-in toggles only today, next day accumulates one record',()=>{let w=fixture(true);const id=w.tasks[0].id;w=applyOperation(w,{kind:'complete',id},now);assert.deepEqual(w.tasks[0].completions,['2026-09-10']);w=applyOperation(w,{kind:'complete',id},now);assert.deepEqual(w.tasks[0].completions,[]);w=applyOperation(w,{kind:'complete',id},now);w=applyOperation(w,{kind:'complete',id},new Date('2026-09-10T16:00:00Z'));assert.deepEqual(w.tasks[0].completions,['2026-09-10','2026-09-11']);assert.equal(w.tasks.length,1);assert.notEqual(w.tasks[0].status,'已结束');});
test('paused routines reject check-in',()=>{let w=fixture(true);w.tasks[0].status='暂停';assert.throws(()=>applyOperation(w,{kind:'complete',id:w.tasks[0].id},now),/暂停/);});
test('delete restore preserves content, priorities, color, completion history',()=>{let w=fixture(true);const id=w.tasks[0].id;w=applyOperation(w,{kind:'complete',id},now);w=applyOperation(w,{kind:'delete',id},now);assert.ok(w.tasks[0].deletedAt);assert.throws(()=>applyOperation(w,{kind:'flag',id},now),/恢复/);w=applyOperation(w,{kind:'restore',id},now);assert.equal(w.tasks[0].notes,'保留备注');assert.equal(w.tasks[0].coordOrder,1);assert.equal(w.tasks[0].color,'#bc9bf5');assert.deepEqual(w.tasks[0].completions,['2026-09-10']);});
test('one-time completion and reopen; boost does not change original priorities',()=>{let w=fixture();const id=w.tasks[0].id;w=applyOperation(w,{kind:'boost',id,reason:'本次先做'},now);assert.equal(w.tasks[0].coordOrder,1);assert.equal(w.tasks[0].boostDate,'2026-09-10');w=applyOperation(w,{kind:'complete',id},now);assert.equal(w.tasks[0].status,'已结束');w=applyOperation(w,{kind:'reopen',id},now);assert.equal(w.tasks[0].status,'准备推进');});
test('validation rejects malformed inputs before persistence',()=>{const task={...newTask(),title:'有效'};assert.throws(()=>validateTask({...task,title:''}));assert.throws(()=>validateTask({...task,coordOrder:-1}));assert.throws(()=>validateTask({...task,coordLetter:'NA',coordOrder:2}));assert.throws(()=>validateTask({...task,minutes:-1}));assert.throws(()=>validateTask({...task,start:'2026-02-30T10:00'}));assert.throws(()=>validateTask({...task,start:'2026-09-10T11:00',end:'2026-09-10T10:00'}));assert.throws(()=>validateTask({...task,color:'red'}));});
test('backup import validates duplicate ids and retains task history/settings',()=>{let w=fixture(true);w=applyOperation(w,{kind:'complete',id:w.tasks[0].id},now);w.settings.density='comfortable';assert.throws(()=>validateImport({...w,tasks:[...w.tasks,...w.tasks]}),/重复/);const restored=applyOperation(emptyWorkspace('personal'),{kind:'import',data:JSON.parse(JSON.stringify(w))},now);assert.deepEqual(restored.tasks[0].completions,w.tasks[0].completions);assert.equal(restored.tasks[0].color,w.tasks[0].color);assert.equal(restored.settings.density,'comfortable');});
