import test from 'node:test';
import assert from 'node:assert/strict';
import {TIME_SLOTS_PER_DAY,TIME_SLOT_MS,summarizeTimeSlot,timeSlotClock} from '../lib/time-grid.ts';
const base=Date.parse('2026-09-23T14:00:00+08:00'),range=(a:number,b:number,categoryId:string)=>({start:new Date(base+a*60000).toISOString(),end:new Date(base+b*60000).toISOString(),categoryId});
void test('ten minute slots cover midnight exactly',()=>{assert.equal(TIME_SLOTS_PER_DAY,144);assert.equal(TIME_SLOT_MS,600000);assert.equal(timeSlotClock(143),'23:50');assert.equal(timeSlotClock(144),'00:00');});
void test('dominant color totals disjoint fragments of the same category',()=>{const s=summarizeTimeSlot([range(0,3,'study'),range(3,7,'meal'),range(7,10,'study')],base,base+600000);assert.equal(s.categoryId,'study');assert.deepEqual(s.parts,[{categoryId:'study',minutes:6},{categoryId:'meal',minutes:4}]);});
void test('unrecorded dominates sparse entries; tie prefers actual with stable ordering',()=>{assert.equal(summarizeTimeSlot([range(0,2,'study')],base,base+600000).categoryId,'unrecorded');assert.equal(summarizeTimeSlot([range(0,5,'study')],base,base+600000).categoryId,'study');const rows=[range(5,10,'meal'),range(0,5,'study')];assert.equal(summarizeTimeSlot(rows,base,base+600000).categoryId,'study');assert.equal(summarizeTimeSlot(rows.reverse(),base,base+600000).categoryId,'study');});
void test('future portions never compete; plan is hollow and not actual',()=>{assert.equal(summarizeTimeSlot([range(0,2,'study')],base,base+120000).categoryId,'study');assert.equal(summarizeTimeSlot([],base,base-1).state,'future');const p=summarizeTimeSlot([],base,base-1,[range(0,10,'class')]);assert.equal(p.state,'planned');assert.equal(p.minutes,0);});
void test('85 minute record stays exact across nine display cells',()=>{const rows=[range(10,95,'study')];let total=0;for(let i=0;i<12;i++)total+=summarizeTimeSlot(rows,base+i*TIME_SLOT_MS,base+120*60000).parts.filter(p=>p.categoryId==='study').reduce((n,p)=>n+p.minutes,0);assert.equal(total,85);});
