import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync,readdirSync} from 'node:fs';
import {Store} from '../lib/storage-v2.ts';
import {newTask,type Task} from '../lib/domain.ts';
import {sha256,mergeThreeWay,applyTaskMutation,type Mutation} from '../lib/protocol.ts';
import type {Workspace} from '../lib/workspace.ts';
import {setup} from './d1-helper.ts';
function mutation(task:Task,operation:Mutation['operation'],id=crypto.randomUUID()):Mutation{return {space:'personal',clientId:'client-a',operationId:id,taskId:task.id,baseVersion:task.version,operation};}
async function create(store:Store,fields:Partial<Task>={}){const t={...newTask(),title:'合成事项',...fields};return (await store.mutate(mutation(t,{kind:'create',task:t}))).task!;}
function source():Workspace{const t={...newTask('research'),id:'source-a',title:'测试·无损',version:7,createdAt:'2026-01-01T01:02:03.000Z',updatedAt:'2026-08-01T04:05:06.000Z',due:'2026-09-30',priority:'A+',coordLetter:'NA',notes:' 前后空格与换行\\n🦊 ',color:'#aabbcc',daily:true,completions:['2026-08-02','2026-07-01'],checklist:[{id:'z',text:'最后',done:false},{id:'a',text:'第一',done:true}]};return {schemaVersion:1,space:'personal',revision:31,settings:{density:'comfortable'},tasks:[t,{...t,id:'source-b',title:'软删除事项',deletedAt:'2026-08-02T00:00:00Z'}]};}
test('v2 different tasks write concurrently; same field cannot overwrite',async()=>{const {store}=await setup(),a=await create(store),b=await create(store);await Promise.all([store.mutate(mutation(a,{kind:'patch',patch:{title:'A'}})),store.mutate(mutation(b,{kind:'patch',patch:{title:'B'}}))]);const current=(await store.task('personal',a.id))!;const results=await Promise.allSettled([store.mutate(mutation(current,{kind:'patch',patch:{notes:'one'}})),store.mutate(mutation(current,{kind:'patch',patch:{notes:'two'}}))]);assert.equal(results.filter(x=>x.status==='fulfilled').length,1);assert.equal(results.filter(x=>x.status==='rejected').length,1);});
test('v2 repeated and concurrent operation IDs return exactly one receipt',async()=>{const {store,sqlite}=await setup();const t={...newTask(),title:'仅一张'};const m=mutation(t,{kind:'create',task:t});const [a,b]=await Promise.all([store.mutate(m),store.mutate(m)]);assert.deepEqual(a,b);assert.equal((await store.snapshot('personal')).workspace.tasks.length,1);assert.equal(sqlite.prepare('SELECT COUNT(*) n FROM mutation_receipts').get()!.n,1);await assert.rejects(()=>store.mutate({...m,operation:{kind:'create',task:{...t,title:'改写请求'}}}));});
test('v2 stale mutation rolls back receipt, task and log',async()=>{const {store,sqlite}=await setup();const t=await create(store);await store.mutate(mutation(t,{kind:'setFlagged',value:true}));const before=await store.snapshot('personal');await assert.rejects(()=>store.mutate(mutation(t,{kind:'patch',patch:{title:'不该保存'}})));assert.deepEqual(await store.snapshot('personal'),before);assert.equal(sqlite.prepare('SELECT COUNT(*) n FROM change_log').get()!.n,2);assert.equal(sqlite.prepare('SELECT COUNT(*) n FROM mutation_receipts').get()!.n,2);});
test('v2 transaction rolls back after log failure and zero-row receipt update',async()=>{const {store,sqlite}=await setup();const t=await create(store);sqlite.exec("CREATE TRIGGER block_log BEFORE INSERT ON change_log BEGIN SELECT RAISE(ABORT,'injected'); END;");await assert.rejects(()=>store.mutate(mutation(t,{kind:'setFlagged',value:true})));assert.equal((await store.task('personal',t.id))!.flagged,false);sqlite.exec('DROP TRIGGER block_log');sqlite.exec('CREATE TRIGGER ignore_receipt BEFORE UPDATE ON mutation_receipts BEGIN SELECT RAISE(IGNORE); END;');await assert.rejects(()=>store.mutate(mutation(t,{kind:'setFlagged',value:true})));assert.equal((await store.task('personal',t.id))!.version,t.version);});
test('v2 explicit daily target replays once and records selected Beijing date',async()=>{const {store}=await setup();const t=await create(store,{daily:true});const m=mutation(t,{kind:'setCompleted',value:true,date:'2026-09-09',capturedAt:'2026-09-09T15:59:59Z'});await store.mutate(m);await store.mutate(m);let latest=(await store.task('personal',t.id))!;assert.deepEqual(latest.completions,['2026-09-09']);latest=(await store.mutate(mutation(latest,{kind:'setCompleted',value:false,date:'2026-09-09',capturedAt:'2026-09-09T15:59:59Z'}))).task!;assert.deepEqual(latest.completions,[]);});
test('v2 delete/edit conflict cannot resurrect; explicit restore retains records',async()=>{const {store}=await setup();const t=await create(store,{daily:true,notes:'保留备注'});const done=(await store.mutate(mutation(t,{kind:'setCompleted',value:true,date:'2026-09-09',capturedAt:'2026-09-09T00:00:00Z'}))).task!;const deleted=(await store.mutate(mutation(done,{kind:'setDeleted',value:true}))).task!;await assert.rejects(()=>store.mutate(mutation(done,{kind:'patch',patch:{notes:'离线编辑'}})));await assert.rejects(()=>store.mutate(mutation(deleted,{kind:'patch',patch:{notes:'试图复活'}})));const restored=(await store.mutate(mutation(deleted,{kind:'setDeleted',value:false}))).task!;assert.deepEqual(restored.completions,done.completions);assert.equal(restored.notes,'保留备注');});
test('v2 migration is lossless including order, versions, tombstones; retry idempotent',async()=>{const {store}=await setup();const w=source(),preview=await store.preview('personal',w,'migration');const first=await store.importWorkspace('personal',w,'import-1',preview.sourceHash,0,'migration');assert.deepEqual(await store.importWorkspace('personal',w,'import-1',preview.sourceHash,0,'migration'),first);assert.deepEqual((await store.snapshot('personal')).workspace,w);await assert.rejects(async()=>store.importWorkspace('personal',{...w,tasks:[...w.tasks,{...w.tasks[0],id:'extra'}]},'import-1',await sha256({...w,tasks:[...w.tasks,{...w.tasks[0],id:'extra'}]}),0,'migration'));});
test('v2 restore retains pre-restore snapshot and tombstones omitted rows',async()=>{const {store}=await setup();const w=source();await store.importWorkspace('personal',w,'import-1',await sha256(w),0,'migration');const extra=await create(store,{title:'恢复时不存在于备份'}),before=(await store.snapshot('personal')).workspace;const preview=await store.preview('personal',w,'restore');await store.importWorkspace('personal',w,'restore-1',preview.sourceHash,preview.expectedRevision,'restore');assert.ok((await store.task('personal',extra.id))!.deletedAt);const snapshot=await store.q('SELECT payload FROM snapshots_v2 WHERE owner_id=? AND space=? AND id=?',store.owner,'personal','restore-1').first<{payload:string}>();assert.deepEqual(JSON.parse(snapshot!.payload),before);});
test('v2 owner and workspace isolation',async()=>{const {store,db}=await setup(),other=new Store(db,'owner-b');await other.initialize('subject-b');const t=await create(store);assert.equal(await other.task('personal',t.id),null);assert.equal((await store.snapshot('demo')).workspace.tasks.length,0);await assert.rejects(()=>other.mutate(mutation(t,{kind:'patch',patch:{title:'越权'}})));assert.equal((await other.snapshot('personal')).workspace.tasks.length,0);});
test('v2 cursor reset and page boundary do not skip changes',async()=>{const {store}=await setup();let t=await create(store);for(let i=0;i<105;i++)t=(await store.mutate(mutation(t,{kind:'setFlagged',value:i%2===0}))).task!;const page1=await store.sync('personal',0);assert.equal(page1.changes!.length,100);assert.equal(page1.nextCursor,100);assert.equal(page1.hasMore,true);const page2=await store.sync('personal',page1.nextCursor);assert.equal(page2.changes!.length,6);assert.equal(page2.nextCursor,106);await assert.rejects(()=>store.sync('personal',999));});
test('v2 three-way merge detects same-field and checklist conflict',()=>{const base={...newTask(),title:'旧标题'};const local={...base,title:'本机标题'},remote={...base,notes:'云端备注'};const merge=mergeThreeWay(base,local,remote);assert.equal(merge.merged.title,'本机标题');assert.equal(merge.merged.notes,'云端备注');assert.deepEqual(merge.conflicts,[]);assert.deepEqual(mergeThreeWay(base,local,{...remote,title:'云端标题'}).conflicts,['title']);});
test('v2 server rejects future check-ins and system-field patch',()=>{const t={...newTask(),title:'事项',version:1,daily:true};assert.throws(()=>applyTaskMutation(t,mutation(t,{kind:'setCompleted',value:true,date:'2026-09-11',capturedAt:'2026-09-10T00:00:00Z'}),new Date('2026-09-10T00:00:00Z')));assert.throws(()=>applyTaskMutation(t,mutation(t,{kind:'patch',patch:{version:10} as any})));});
// Public fixtures are generated in memory; no captured user workspace is required.
test('synthetic workspaces migrate and restore without losing any task field',async()=>{for(const space of ['personal','demo'] as const){const w={...source(),space};const {store}=await setup();const p=await store.preview(space,w,'migration');await store.importWorkspace(space,w,'synthetic-roundtrip',p.sourceHash,0,'migration');assert.deepEqual((await store.snapshot(space)).workspace,w);const restored=await setup();await restored.store.importWorkspace(space,(await store.snapshot(space)).workspace,'recovery-drill',p.sourceHash,0,'migration');assert.deepEqual((await restored.store.snapshot(space)).workspace,w);}});
test('empty workspace migration preserves revision zero exactly',async()=>{const {store}=await setup();const w=(await store.snapshot('personal')).workspace;const p=await store.preview('personal',w,'migration');await store.importWorkspace('personal',w,'empty-zero',p.sourceHash,0,'migration');assert.deepEqual((await store.snapshot('personal')).workspace,w);});
