"use client";
import {useState} from 'react';
import {type QueueItem,type SyncEngine,type CategoryField} from '@/lib/client-sync';
import type {EditableKey} from '@/lib/protocol';
const labels:Partial<Record<EditableKey,string>>={title:'事项名称',notes:'备注',priority:'本流优先级',coordLetter:'协调字母',coordOrder:'协调数字',status:'状态',checklist:'检查清单',start:'开始日期',end:'结束日期',due:'截止日期',flow:'工作流',color:'颜色',project:'直属 / 项目文本',kind:'事项类型',projectId:'关联项目',location:'地点',emergency:'紧急',flagged:'旗标',daily:'每日重复'};
function CategoryConflict({item,engine}:{item:QueueItem;engine:SyncEngine}){const [choices,setChoices]=useState<Partial<Record<CategoryField,'local'|'remote'>>>({}),[error,setError]=useState('');const names:Record<CategoryField,string>={name:'分类全名',displayLabel:'卡面简称',color:'背景颜色',archived:'停用状态'};async function resolve(discard=false){try{await engine.resolveCategory(item.mutation.operationId,choices,discard);}catch(e){setError((e as Error).message);}}return <section className="conflict-panel" aria-label="分类同步冲突"><h3>分类：{item.categoryLocal?.name}</h3><p>{item.error||'分类操作尚未同步'}</p>{item.categoryConflicts?.map(field=><fieldset key={field}><legend>{names[field]}</legend>{(['local','remote'] as const).map(side=><label key={side}><input type="radio" name={item.mutation.operationId+field} checked={choices[field]===side} onChange={()=>setChoices(v=>({...v,[field]:side}))}/>{side==='local'?'本机':'云端'}<pre>{JSON.stringify((side==='local'?item.categoryLocal:item.categoryLatest)?.[field])}</pre></label>)}</fieldset>)}<div className="data-buttons">{item.queueConflict&&<button className="btn" onClick={()=>void engine.resolveQueue(item.mutation.operationId).catch(e=>setError(e.message))}>核对后按当前队列重新执行</button>}{item.state==='failed'?<button className="btn" onClick={()=>void engine.retry(item.mutation.operationId)}>重试原操作</button>:!!item.categoryConflicts?.length&&<button className="btn" onClick={()=>void resolve()}>保存所选版本</button>}<button className="btn" onClick={()=>void resolve(true)}>保留云端版本</button></div><p>关联卡片等待分类处理完成；草稿可从同步面板导出。</p>{error&&<p role="alert">{error}</p>}</section>;}
export function ConflictPanel({item,engine}:{item:QueueItem;engine:SyncEngine}){const [choices,setChoices]=useState<Partial<Record<EditableKey,'local'|'remote'>>>({}),[error,setError]=useState('');async function resolve(copy=false,discard=false){try{await engine.resolve(item.mutation.operationId,choices,copy,discard);}catch(e){setError((e as Error).message);}}
if(item.categoryLocal)return <CategoryConflict item={item} engine={engine}/>;
return <section className="conflict-panel" aria-label="同步冲突"><h3>{item.local?.title||'显示设置'}</h3><p>{item.error||'操作尚未同步'}</p>{item.mutation.operation.kind==='patch'&&item.fields?.map(field=><fieldset key={field}><legend>{labels[field]||field}</legend>{(['local','remote'] as const).map(side=><label key={side}><input type="radio" name={item.mutation.operationId+field} checked={choices[field]===side} onChange={()=>setChoices(v=>({...v,[field]:side}))}/>{side==='local'?'本机':'云端'}<pre>{JSON.stringify((side==='local'?item.local:item.latest)?.[field],null,2)}</pre></label>)}</fieldset>)}<div className="data-buttons">{item.queueConflict&&<button className="btn" onClick={()=>void engine.resolveQueue(item.mutation.operationId).catch(e=>setError(e.message))}>核对后按当前队列重新执行</button>}{item.state==='failed'?<button className="btn" onClick={()=>void engine.retry(item.mutation.operationId)}>重试原操作</button>:item.latest&&!item.latest.deletedAt&&item.mutation.operation.kind==='patch'&&<button className="btn" onClick={()=>void resolve()}>保存所选版本</button>}{item.state==='conflict'&&item.latest&&item.mutation.operation.kind!=='patch'&&item.mutation.operation.kind!=='create'&&(!item.latest.deletedAt||(item.mutation.operation.kind==='setDeleted'&&!item.mutation.operation.value))&&<button className="btn" onClick={()=>void resolve()}>确认仍执行本机操作</button>}{item.local&&<button className="btn" onClick={()=>void resolve(true)}>草稿另存为新卡片</button>}<button className="btn" onClick={()=>void resolve(false,true)}>保留云端版本</button></div>{error&&<p role="alert">{error}</p>}</section>;}
