'use client';
import {useMemo,useState,useEffect,useRef} from 'react';
import {ResponsiveContainer,PieChart,Pie,Cell,Tooltip,RadarChart,PolarGrid,PolarAngleAxis,PolarRadiusAxis,Radar} from 'recharts';
import {ATTENDANCE_LABELS,attendanceTotals,categoryTotals,weeklyComparison,type Attendance} from '../lib/time-analytics';
import {shanghaiDate,localClock,type TimeCategory,type TimeInterval,type TimePlan,type TimeMutation} from '../lib/time-client';
type Slice={id:string;name:string;color:string;value:number};
const format=(minutes:number)=>{const rounded=Math.round(minutes);return `${Math.floor(rounded/60)}h ${rounded%60}m`;};
const weekColors=['#8b969e','#B39AE7','#EDA66C','#73C6A2'];
function Donut({data,unit,caption}:{data:Slice[];unit:string;caption:string}){
 const total=data.reduce((s,d)=>s+d.value,0),shown=data.filter(d=>d.value>0);
 return <div className="time-donut-body"><div className="time-donut-plot" role="img" aria-label={caption+'：'+shown.map(d=>d.name+' '+(unit==='分钟'?format(d.value):d.value+'节')).join('，')}>
 {total?<ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={shown} dataKey="value" nameKey="name" innerRadius="58%" outerRadius="88%" paddingAngle={shown.length>1?2:0} isAnimationActive={false} stroke="none">{shown.map(d=><Cell key={d.id} fill={d.color}/>)}</Pie><Tooltip formatter={(value)=>unit==='分钟'?format(Number(value)):Number(value)+'节'} contentStyle={{background:'var(--time-surface)',border:'1px solid var(--time-border)',color:'var(--time-fg)',fontSize:11}}/></PieChart></ResponsiveContainer>:<span className="time-chart-empty">暂无记录</span>}
 <div className="time-donut-center"><strong>{unit==='分钟'?(total/60).toFixed(1):total}</strong><span>{unit==='分钟'?'小时':'节课'}</span></div></div><div className="time-chart-legend">{data.map(d=><div key={d.id} title={d.name+' '+(unit==='分钟'?format(d.value):d.value+'节')}><i style={{background:d.color}}/><span>{d.name}</span><b>{total?(100*d.value/total).toFixed(1):'0'}%</b><small>{unit==='分钟'?format(d.value):d.value+'节'}</small></div>)}</div></div>;
}
export function TimeAnalytics({rows,plans,categories,now,act,onSettings}:{rows:TimeInterval[];plans:TimePlan[];categories:TimeCategory[];now:number;act:(m:TimeMutation)=>Promise<void>;onSettings:()=>void}){
 const [range,setRange]=useState(7),[attendanceOpen,setAttendanceOpen]=useState(false),[saving,setSaving]=useState(''),[notice,setNotice]=useState('');
 const dialog=useRef<HTMLDivElement>(null),[weekCount,setWeekCount]=useState(2);
 useEffect(()=>{if(!attendanceOpen)return;const prior=document.activeElement as HTMLElement|null;dialog.current?.querySelector<HTMLElement>('button')?.focus();const key=(e:KeyboardEvent)=>{if(e.key==='Escape')setAttendanceOpen(false);if(e.key==='Tab'){const items=[...dialog.current!.querySelectorAll<HTMLElement>('button:not(:disabled),select:not(:disabled)')],first=items[0],last=items.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}};document.addEventListener('keydown',key);return()=>{document.removeEventListener('keydown',key);prior?.focus();};},[attendanceOpen]);
 const start=now-range*86400000;
 const totals=useMemo(()=>categoryTotals(rows,categories,start,now),[rows,categories,start,now]);
 const recorded=totals.reduce((s,d)=>s+d.value,0),unknown=Math.max(0,range*1440-recorded);
 const timeSlices=useMemo(()=>{const ordered=totals.filter(d=>d.value>0).sort((a,b)=>b.value-a.value);return ordered.length<=6?ordered:[...ordered.slice(0,5),{id:'remaining',name:'其余类别',color:'#9da68e',value:ordered.slice(5).reduce((s,d)=>s+d.value,0)}];},[totals]);
 const attendance=useMemo(()=>attendanceTotals(plans,start,now),[plans,start,now]);
 const weeks=useMemo(()=>weeklyComparison(rows,categories,now,weekCount),[rows,categories,now,weekCount]);
 const ended=plans.filter(p=>p.categoryId==='class'&&Date.parse(p.end)>start&&Date.parse(p.end)<=now&&(p.status!=='cancelled'||!!p.attendance)).sort((a,b)=>b.start.localeCompare(a.start));
 return <div className="time-analytics"><div className="time-analytics-toolbar"><h3>时间洞察</h3><div role="group" aria-label="图表统计范围">{[1,7,30].map(n=><button key={n} aria-pressed={range===n} onClick={()=>setRange(n)}>近{n===1?'一天':n===7?'一周':'一月'}</button>)}</div><button onClick={onSettings}>分类</button></div>
 <div className="time-chart-grid"><section className="time-chart-card" aria-labelledby="time-share-heading"><div className="time-section-head"><h3 id="time-share-heading">时间占比</h3><span>已记录时间</span></div><Donut data={timeSlices} unit="分钟" caption="时间占比"/><p className="time-chart-note">未记录 {format(unknown)} · 占比仅含已记录时间</p></section>
 <section className="time-chart-card" aria-labelledby="time-attendance-heading"><div className="time-section-head"><h3 id="time-attendance-heading">课程出勤</h3><button onClick={()=>setAttendanceOpen(true)}>标注出勤</button></div><Donut data={attendance} unit="节" caption="已结束课程出勤分布"/><p className="time-chart-note">已结束节次 · 含待标注 · “上过”不推定准时</p></section>
 <section className="time-chart-card time-radar-card" aria-labelledby="time-week-heading"><div className="time-section-head"><h3 id="time-week-heading">周度时间对比</h3><select aria-label="比较周数" value={weekCount} onChange={e=>setWeekCount(Number(e.target.value))}><option value={2}>最近 2 个完整周</option><option value={4}>最近 4 个完整周</option></select><span>小时 / 周 · 同一刻度</span></div><div className="time-radar-body"><div className="time-radar-plot" role="img" aria-label="按类别比较最近完整周的实际小时数"><ResponsiveContainer width="100%" height="100%"><RadarChart data={weeks.axes} outerRadius="68%"><PolarGrid stroke="var(--time-border)"/><PolarAngleAxis dataKey="name" tick={{fontSize:10,fill:'var(--time-fg)'}}/><PolarRadiusAxis domain={[0,'auto']} tick={{fontSize:9,fill:'var(--time-muted)'}} tickCount={4}/>{weeks.series.map((w,i)=><Radar key={w.key} name={w.label+' 起始周'} dataKey={w.key} stroke={weekColors[4-weekCount+i]} fill={weekColors[4-weekCount+i]} fillOpacity={.06} strokeWidth={2} strokeDasharray={i===0?'4 3':undefined} isAnimationActive={false}/>)}<Tooltip formatter={(value)=>Number(value).toFixed(2)+' 小时'} contentStyle={{background:'var(--time-surface)',border:'1px solid var(--time-border)',fontSize:11}}/></RadarChart></ResponsiveContainer></div><div className="time-week-legend">{weeks.series.map((w,i)=>{const total=weeks.axes.reduce((s,a)=>s+Number((a as Record<string,unknown>)[w.key]),0);return <div key={w.key}><i style={{background:weekColors[4-weekCount+i]}}/><span>{w.label} — {shanghaiDate(w.end-1).slice(5)}</span><b>{total.toFixed(1)} h</b></div>;})}<p>仅统计实际记录；缺失记录不等于没有活动。本周尚未结束，暂不参与完整周对比。</p><details><summary>查看各类别准确数值</summary><table><thead><tr><th>类别 / h</th>{weeks.series.map(w=><th key={w.key}>{w.label}</th>)}</tr></thead><tbody>{weeks.axes.map(a=><tr key={a.id}><th>{a.name}</th>{weeks.series.map(w=><td key={w.key}>{Number((a as Record<string,unknown>)[w.key]).toFixed(2)}</td>)}</tr>)}</tbody></table></details></div></div></section></div>
 <p className="time-chart-source">实际时间与课程计划 · 近 {range}×24 小时，截至 {shanghaiDate(now)} {localClock(new Date(now).toISOString())}</p>
 {attendanceOpen&&<div className="time-overlay"><div ref={dialog} className="time-dialog wide time-attendance-dialog" role="dialog" aria-modal="true" aria-labelledby="attendance-title"><div className="time-section-head"><h2 id="attendance-title">课程出勤标注</h2><button onClick={()=>setAttendanceOpen(false)}>关闭</button></div><p>近 {range} 天已结束课程。出勤标注独立于实际时间：如需扣除迟到时长，请在日时间轴修改准确区间。</p>{!ended.length&&<p>此范围没有已结束的课程计划。</p>}<div className="time-attendance-list">{ended.map(p=><label key={p.id}><span><b>{shanghaiDate(Date.parse(p.start))} {localClock(p.start)}—{localClock(p.end)}</b><small>{p.note||'课程'}{p.status==='confirmed'?' · 已确认上过':''}</small></span><select aria-label={shanghaiDate(Date.parse(p.start))+' '+localClock(p.start)+' 出勤状态'} value={p.attendance||''} disabled={!!saving||p.status==='cancelled'} onChange={async e=>{const status=e.target.value as Attendance;setSaving(p.id);setNotice('正在保存出勤标注…');try{await act({type:'setAttendance',id:p.id,status});setNotice('已提交，请以顶部同步状态为准。');}finally{setSaving('');}}}><option value="" disabled>待标注</option>{Object.entries(ATTENDANCE_LABELS).map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label>)}</div><p role="status">{notice}</p></div></div>}
 </div>;
}
