import type {Store} from './storage-v2.ts';
import type {Task} from './domain.ts';
import {today} from './domain.ts';
import type {TaskEvent} from './analytics.ts';
import {normalizeQueue,coordinateMutation} from './coordination.ts';
import {AppError,validateTaskRelations,type HistoryData} from './workspace.ts';
import {applyTaskMutation,checkMutation,ConflictError,sha256,stable,type Mutation,type Space,type Receipt} from './protocol.ts';
export type CoordinationState={ready:number;queue_version:number;coverage:string};
export async function coordinationState(store:Store,space:Space):Promise<CoordinationState>{return await store.q('SELECT ready,queue_version,coverage FROM coordination_state WHERE owner_id=? AND space=?',store.owner,space).first<CoordinationState>()||{ready:0,queue_version:0,coverage:JSON.stringify({since:today(),incomplete:true,unknown:0})};}
export async function readHistory(store:Store,space:Space):Promise<HistoryData>{const rows=await store.db.batch([store.q('SELECT coverage FROM coordination_state WHERE owner_id=? AND space=?',store.owner,space),store.q('SELECT payload FROM task_events WHERE owner_id=? AND space=? ORDER BY event_id',store.owner,space)]);return {version:1,events:rows[1].results.map(x=>JSON.parse((x as {payload:string}).payload)),coverage:rows[0].results.length?JSON.parse((rows[0].results[0] as {coverage:string}).coverage):{since:today(),incomplete:true,unknown:0}};}
export function writeEvents(store:Store,space:Space,events:TaskEvent[]){return events.length?[store.q("INSERT INTO task_events(owner_id,space,event_id,task_id,kind,date,payload) SELECT ?,?,json_extract(value,'$.id'),json_extract(value,'$.taskId'),json_extract(value,'$.kind'),json_extract(value,'$.date'),value FROM json_each(?) WHERE true ON CONFLICT(owner_id,space,event_id) DO NOTHING",store.owner,space,JSON.stringify(events))]:[];}
export function taskWrites(store:Store,space:Space,tasks:Task[]){return tasks.length?[store.q("INSERT INTO tasks(owner_id,space,task_id,version,flow,status,deleted_at,updated_at,payload,ordinal) SELECT ?,?,json_extract(value,'$.id'),json_extract(value,'$.version'),json_extract(value,'$.flow'),json_extract(value,'$.status'),json_extract(value,'$.deletedAt'),json_extract(value,'$.updatedAt'),json_remove(value,'$.completions'),(SELECT COALESCE(MAX(ordinal),-1)+1 FROM tasks WHERE owner_id=? AND space=?)+CAST(key AS INTEGER) FROM json_each(?) WHERE true ON CONFLICT(owner_id,space,task_id) DO UPDATE SET version=excluded.version,flow=excluded.flow,status=excluded.status,deleted_at=excluded.deleted_at,updated_at=excluded.updated_at,payload=excluded.payload",store.owner,space,store.owner,space,JSON.stringify(tasks))]:[];}
function liveEvents(old:Task|null,next:Task,m:Mutation,history:TaskEvent[],stamp:string):TaskEvent[]{
 const occurredAt=m.capturedAt||stamp;if(!Number.isFinite(Date.parse(occurredAt))||Date.parse(occurredAt)>Date.parse(stamp)+300000)throw new AppError('设备时间无效，请校准后重试');
 const result:TaskEvent[]=[],reversed=new Set(history.filter(e=>e.kind==='revoked').map(e=>e.reverses));
 const add=(kind:TaskEvent['kind'],date=today(new Date(occurredAt)),daily=false,reverses?:string)=>result.push({id:m.operationId+'-'+kind,taskId:next.id,kind,date,flow:next.flow,daily,occurredAt,reverses,source:'live'});
 if(!old)add('created');
 if(m.operation.kind==='setCompleted'){
  const op=m.operation,was=old?.completions.includes(op.date)||false;
  if(op.value&&!was)add('completed',op.date,true);
  if(!op.value&&was)for(const e of history.filter(e=>e.taskId===next.id&&e.kind==='completed'&&e.daily&&e.date===op.date&&!reversed.has(e.id)))result.push({id:m.operationId+'-revoke-'+e.id,taskId:next.id,kind:'revoked',date:e.date,flow:e.flow,daily:true,occurredAt,reverses:e.id,source:'live'});
 }else{
  if(!next.daily&&next.status==='已结束'&&old?.status!=='已结束')add('completed');
  if(old?.status==='已结束'&&next.status!=='已结束')for(const e of history.filter(e=>e.taskId===next.id&&e.kind==='completed'&&!e.daily&&!reversed.has(e.id)))result.push({id:m.operationId+'-revoke-'+e.id,taskId:next.id,kind:'revoked',date:e.date,flow:e.flow,daily:false,occurredAt,reverses:e.id,source:'live'});
 }
 return result;
}
export async function coordinationPreview(store:Store,space:Space){const {workspace}=await store.snapshot(space);const normalized=normalizeQueue(workspace.tasks);return {expectedRevision:workspace.revision,ready:!!(await coordinationState(store,space)).ready,changes:normalized.filter((t,i)=>stable(t)!==stable(workspace.tasks[i])).map(t=>({id:t.id,title:t.title,from:workspace.tasks.find(x=>x.id===t.id)?.coordOrder,to:t.coordOrder})),taskCount:workspace.tasks.length};}
export async function enableCoordination(store:Store,space:Space,expectedRevision:number){
 const current=await store.snapshot(space),before=current.workspace;if(before.revision!==expectedRevision)throw new ConflictError(null);const state=await coordinationState(store,space);if(state.ready)return {ready:true,revision:before.revision};
 const stamp=new Date().toISOString(),runId='coordination-'+crypto.randomUUID();const normalized=normalizeQueue(before.tasks);const changed=normalized.filter((t,i)=>stable(t)!==stable(before.tasks[i])).map(t=>({...t,version:t.version+1,updatedAt:stamp}));
 const logs=(await store.q('SELECT seq,kind,dto_json,created_at FROM change_log WHERE owner_id=? AND space=? ORDER BY seq',store.owner,space).all<{seq:number;kind:string;dto_json:string;created_at:string}>()).results;
 const events:TaskEvent[]=[],known=new Map<string,Task>(),initialFlow=new Map<string,string>(),active=new Map<string,string>();
 for(const log of logs){if(log.kind==='reset'){known.clear();continue;}const dto=JSON.parse(log.dto_json);for(const task of dto.tasks|| (dto.task?[dto.task]:[])){const prior=known.get(task.id);if(task.version===1)initialFlow.set(task.id,task.flow);if(prior&&!task.daily&&prior.status!=='已结束'&&task.status==='已结束'){const id=`historical-complete-${log.seq}-${task.id}`;events.push({id,taskId:task.id,kind:'completed',date:today(new Date(log.created_at)),flow:task.flow,daily:false,occurredAt:log.created_at,source:'historical'});active.set(task.id,id);}if(prior?.status==='已结束'&&task.status!=='已结束'&&active.has(task.id)){const e=events.find(x=>x.id===active.get(task.id))!;events.push({...e,id:'historical-revoke-'+log.seq+'-'+task.id,kind:'revoked',reverses:e.id,occurredAt:log.created_at});active.delete(task.id);}known.set(task.id,task);}}
 let unknown=0;for(const t of before.tasks){const flow=initialFlow.get(t.id)||(t.version===1?t.flow:'');if(!flow)unknown++;events.push({id:'historical-create-'+t.id,taskId:t.id,kind:'created',date:today(new Date(t.createdAt)),flow,daily:false,occurredAt:t.createdAt,source:'historical'});for(const date of t.completions)events.push({id:'historical-daily-'+t.id+'-'+date,taskId:t.id,kind:'completed',date,flow:'',daily:true,occurredAt:date+'T12:00:00+08:00',source:'historical'});if(t.status==='已结束'&&!t.daily&&!active.has(t.id))unknown++;unknown+=t.completions.length;}
 const coverage={since:today(),incomplete:before.tasks.length>0,unknown};const dto={operationId:runId,serverTime:stamp,tasks:changed,queueVersion:1};
 const guard=store.q('INSERT INTO snapshots_v2(owner_id,space,id,payload,created_at) SELECT ?,?,?,?,? WHERE NOT EXISTS(SELECT 1 FROM workspaces_v2 WHERE owner_id=? AND space=? AND revision=?)',store.owner,space,runId,'{}',stamp,store.owner,space,expectedRevision);
 try{await store.db.batch([store.q('INSERT INTO snapshots_v2(owner_id,space,id,payload,created_at) VALUES(?,?,?,?,?)',store.owner,space,runId,JSON.stringify(before),stamp),guard,...taskWrites(store,space,changed),...writeEvents(store,space,events),store.q('INSERT INTO coordination_state(owner_id,space,queue_version,ready,coverage) VALUES(?,?,1,1,?) ON CONFLICT(owner_id,space) DO UPDATE SET queue_version=1,ready=1,coverage=excluded.coverage',store.owner,space,JSON.stringify(coverage)),store.q('UPDATE workspaces_v2 SET revision=revision+1 WHERE owner_id=? AND space=?',store.owner,space),store.q("INSERT INTO change_log(owner_id,space,seq,operation_id,kind,dto_json,created_at) VALUES(?,?,?,?,'reset',?,?)",store.owner,space,expectedRevision+1,runId,JSON.stringify(dto),stamp)]);}catch(e){if((await store.snapshot(space)).workspace.revision!==expectedRevision)throw new ConflictError(null);throw e;}return {ready:true,revision:expectedRevision+1};
}
export async function mutateCoordinated(store:Store,input:unknown):Promise<Receipt>{
 const m=checkMutation(input),hash=await sha256(m),prior=await store.receipt(m.space,m.operationId,hash);if(prior)return prior;
 if(m.protocolVersion!==3)throw new AppError('请更新工作台后再同步，已有草稿保留',426);
 const {workspace,settingsVersion}=await store.snapshot(m.space),state=await coordinationState(store,m.space),stamp=new Date().toISOString();
 if(m.queueVersion!==state.queue_version)throw new ConflictError(m.taskId?await store.task(m.space,m.taskId):null,'QUEUE_VERSION_CONFLICT');
 const old=workspace.tasks.find(t=>t.id===m.taskId)||null;let changed:Task[]=[],next:Task|undefined;let events:TaskEvent[]=[];
 if(m.operation.kind==='settings'){if(m.baseVersion!==settingsVersion)throw new ConflictError(null,'SETTINGS_CONFLICT',workspace.settings,settingsVersion);if(!['compact','comfortable'].includes(m.operation.density))throw new AppError('显示密度无效');}
 else {next=applyTaskMutation(old,m,new Date(stamp));if(!old&&workspace.tasks.length>=5000)throw new AppError('事项已达5000张上限');const category=next.categoryId?workspace.settings.categories?.find(item=>item.id===next!.categoryId):undefined;if(next.categoryId&&(!category||category.flow!==next.flow||(category.archived&&old?.categoryId!==next.categoryId)))throw new ConflictError(old,'CATEGORY_CONFLICT',workspace.settings,settingsVersion);const all=coordinateMutation(workspace.tasks,old,next,m.operation as unknown as {kind:string;[key:string]:unknown},m.operation.kind==='setCompleted'?m.operation.date:today());validateTaskRelations(all);changed=all.filter(t=>stable(t)!==stable(workspace.tasks.find(x=>x.id===t.id))).map(t=>({...t,version:(workspace.tasks.find(x=>x.id===t.id)?.version||0)+1,updatedAt:stamp}));next=changed.find(t=>t.id===m.taskId)||next;events=liveEvents(old,next,m,(await readHistory(store,m.space)).events,stamp).map(e=>({...e,sequence:workspace.revision+1}));}
 const queueChanged=changed.some(t=>{const was=workspace.tasks.find(x=>x.id===t.id);return (was?.coordOrder??null)!==t.coordOrder||stable(was?.queueReturn)!==stable(t.queueReturn);});
 const queueVersion=state.queue_version+(queueChanged?1:0),dto:Omit<Receipt,'cursor'>={operationId:m.operationId,serverTime:stamp,tasks:changed,task:next,queueVersion,...(m.operation.kind==='settings'?{settings:{...workspace.settings,density:m.operation.density},settingsVersion:settingsVersion+1}:{})};
 const args=[store.owner,m.space,m.operationId,m.clientId,hash,stamp];const insert='INSERT INTO mutation_receipts(owner_id,space,operation_id,client_id,request_hash,created_at)';const guard=(condition:string,...values:unknown[])=>store.q(insert+' SELECT ?,?,?,?,?,? WHERE '+condition,...args,...values);
 const statements=[store.q(insert+' VALUES(?,?,?,?,?,?)',...args),guard('NOT EXISTS(SELECT 1 FROM workspaces_v2 WHERE owner_id=? AND space=? AND revision=?)',store.owner,m.space,workspace.revision),guard('NOT EXISTS(SELECT 1 FROM coordination_state WHERE owner_id=? AND space=? AND ready=1 AND queue_version=?)',store.owner,m.space,state.queue_version),...taskWrites(store,m.space,changed),...writeEvents(store,m.space,events)];
 if(m.operation.kind==='setCompleted'&&next)statements.push(store.q('INSERT INTO daily_completions(owner_id,space,task_id,beijing_date,completed,version,ordinal) VALUES(?,?,?,?,?,1,?) ON CONFLICT(owner_id,space,task_id,beijing_date) DO UPDATE SET completed=excluded.completed,version=daily_completions.version+1,ordinal=excluded.ordinal',store.owner,m.space,next.id,m.operation.date,m.operation.value?1:0,Math.max(0,next.completions.indexOf(m.operation.date))));
 if(m.operation.kind==='settings')statements.push(store.q('UPDATE workspace_settings SET version=version+1,payload=? WHERE owner_id=? AND space=?',JSON.stringify(dto.settings),store.owner,m.space));
 statements.push(store.q('UPDATE coordination_state SET queue_version=? WHERE owner_id=? AND space=?',queueVersion,store.owner,m.space),store.q('UPDATE workspaces_v2 SET revision=revision+1 WHERE owner_id=? AND space=?',store.owner,m.space),store.q("INSERT INTO change_log(owner_id,space,seq,operation_id,kind,dto_json,created_at) VALUES(?,?,?,?,'batch',?,?)",store.owner,m.space,workspace.revision+1,m.operationId,JSON.stringify(dto),stamp),store.q('UPDATE mutation_receipts SET result_json=?,result_seq=? WHERE owner_id=? AND space=? AND operation_id=?',JSON.stringify(dto),workspace.revision+1,store.owner,m.space,m.operationId));
 try{await store.db.batch(statements);}catch(e){const retry=await store.receipt(m.space,m.operationId,hash);if(retry)return retry;if((await store.snapshot(m.space)).workspace.revision!==workspace.revision)throw new ConflictError(m.taskId?await store.task(m.space,m.taskId):null,'QUEUE_VERSION_CONFLICT');throw e;}return {...dto,cursor:workspace.revision+1};
}
