import {timingSafeEqual} from 'node:crypto';
import {sha256} from './protocol.ts';
import {AppError} from './workspace.ts';
export const SESSION_COOKIE='__Host-qs_session';
const SESSION_SECONDS=30*86400;
export function randomToken(){const bytes=crypto.getRandomValues(new Uint8Array(32));return btoa(String.fromCharCode(...bytes)).replaceAll('+','-').replaceAll('/','_').replaceAll('=','');}
export function sessionToken(request:Request){const matches=(request.headers.get('cookie')||'').split(';').map(x=>x.trim()).filter(x=>x.startsWith(SESSION_COOKIE+'='));if(matches.length!==1)return null;const value=matches[0].slice(SESSION_COOKIE.length+1);return /^[A-Za-z0-9_-]{43}$/.test(value)?value:null;}
function configured(hash:string|undefined):asserts hash is string{if(!hash||!/^[0-9a-f]{64}$/.test(hash))throw new AppError('登录尚未配置',503);}
export async function passcodeIdentity(request:Request,db:D1Database,hash:string|undefined){configured(hash);const token=sessionToken(request);if(!token)throw new AppError('请先登录',401);const row=await db.prepare('SELECT expires_at FROM auth_sessions WHERE token_hash=? AND credential_tag=? AND revoked=0 AND expires_at>?').bind(await sha256(token),hash,Date.now()).first<{expires_at:number}>();if(!row)throw new AppError('登录已过期，请重新登录',401);return {loginId:await sha256(token),owner:'qiushan-owner-v1',subject:'passcode:qiushan-owner-v1',email:'个人口令登录',local:false,expiresAt:row.expires_at};}
export function assertLoginOrigin(request:Request){const u=new URL(request.url);if(u.protocol!=='https:'&&!['127.0.0.1','localhost','[::1]'].includes(u.hostname))throw new AppError('需要安全连接',400);if(request.headers.get('origin')!==u.origin||request.headers.get('sec-fetch-site')==='cross-site')throw new AppError('请求来源不匹配',403);}
async function admission(request:Request,db:D1Database,now:number){const ip=await sha256(request.headers.get('cf-connecting-ip')||'local');const keys=[{key:'ip:'+ip+':'+Math.floor(now/900000),limit:10},{key:'global:'+Math.floor(now/3600000),limit:100}];const rows=await db.batch<{attempts:number}>(keys.map(k=>db.prepare('INSERT INTO auth_attempts(bucket,attempts,expires_at) VALUES(?,1,?) ON CONFLICT(bucket) DO UPDATE SET attempts=attempts+1 RETURNING attempts').bind(k.key,now+86400000)));if(rows.some((r,i)=>Number(r.results[0]?.attempts)>keys[i].limit))throw new AppError('登录尝试过多，请稍后再试',429);}
export async function login(request:Request,db:D1Database,hash:string|undefined){configured(hash);assertLoginOrigin(request);if(!request.headers.get('content-type')?.startsWith('application/x-www-form-urlencoded'))throw new AppError('登录格式无效');await admission(request,db,Date.now());const reader=request.body?.getReader();if(!reader)throw new AppError('缺少口令');const decoder=new TextDecoder();let raw='',size=0;while(true){const r=await reader.read();if(r.done)break;size+=r.value.byteLength;if(size>1024){await reader.cancel();throw new AppError('登录请求过大',413);}raw+=decoder.decode(r.value,{stream:true});}raw+=decoder.decode();const values=new URLSearchParams(raw).getAll('passcode');const passcode=values.length===1?values[0]:'';
 // The credential is generated from 256 random bits, not a human-chosen password.
 // SHA-256 is appropriate for a high-entropy secret; weak custom passwords are not supported.
 const candidate=await sha256(passcode);if(!/^[A-Za-z0-9_-]{43}$/.test(passcode)||!timingSafeEqual(new TextEncoder().encode(candidate),new TextEncoder().encode(hash)))throw new AppError('口令不正确',401);
 const token=randomToken(),now=Date.now();await db.prepare('INSERT INTO auth_sessions(token_hash,credential_tag,expires_at,revoked,created_at) VALUES(?,?,?,0,?)').bind(await sha256(token),hash,now+SESSION_SECONDS*1000,now).run();return new Response(null,{status:303,headers:{Location:new URL(request.url).searchParams.get('next')==='/time'?'/time':'/', 'Set-Cookie':SESSION_COOKIE+'='+token+'; Path=/; Secure; HttpOnly; SameSite=Strict; Max-Age='+SESSION_SECONDS,'Cache-Control':'no-store'}});
}
export async function logout(request:Request,db:D1Database){assertLoginOrigin(request);const token=sessionToken(request);if(token)await db.prepare('UPDATE auth_sessions SET revoked=1 WHERE token_hash=?').bind(await sha256(token)).run();return Response.json({ok:true},{headers:{'Set-Cookie':SESSION_COOKIE+'=; Path=/; Secure; HttpOnly; SameSite=Strict; Max-Age=0','Cache-Control':'no-store'}});}
export function loginPage(message='',status=200,next='/'){const safe=message.replace(/[<>&"']/g,'');return new Response(`<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><title>登录 · 丘山工作台</title><style>html{color-scheme:dark;font-family:system-ui;background:#0d1420;color:#e4eaf0}body{margin:0;min-height:100dvh;display:grid;place-items:center}main{width:min(360px,85vw);padding:32px 0}h1{font-size:26px}p{line-height:1.7;color:#b8c5cf}input,button{box-sizing:border-box;width:100%;min-height:48px;font:inherit;border-radius:9px;margin-top:12px;padding:12px;border:1px solid #445464}button{background:#acd5c6;color:#112820;font-weight:600;cursor:pointer}.error{color:#ffb5ad}label{display:block;margin-top:28px}</style><main><h1>丘山 · 个人工作台</h1><p>输入你的专用口令，在这台设备继续。</p>${safe?'<p class="error" role="alert">'+safe+'</p>':''}<form method="post" action="/login?next=${next==='/time'?'%2Ftime':'%2F'}"><label for="passcode">登录口令</label><input id="passcode" name="passcode" type="password" autocomplete="current-password" required maxlength="100" autofocus><button type="submit">登录工作台</button></form><p>口令保存在你的本机私有文件中。登录过期不会删除已有草稿。</p></main></html>`,{status,headers:{'Content-Type':'text/html;charset=utf-8','Cache-Control':'no-store','X-Content-Type-Options':'nosniff','X-Frame-Options':'DENY','Referrer-Policy':'same-origin','Content-Security-Policy':"default-src 'none'; style-src 'unsafe-inline'; form-action 'self'; frame-ancestors 'none'; base-uri 'none'",...(status===429?{'Retry-After':'3600'}:{})}});}


