import {sqliteTable,text,integer,primaryKey,uniqueIndex,index} from 'drizzle-orm/sqlite-core';
export const workspaces=sqliteTable('workspaces',{id:text('id').primaryKey(),revision:integer('revision').notNull(),payload:text('payload').notNull(),updatedAt:text('updated_at').notNull()});
export const snapshots=sqliteTable('snapshots',{id:text('id').primaryKey(),space:text('space').notNull(),payload:text('payload').notNull(),createdAt:text('created_at').notNull()});
export const owners=sqliteTable('owners',{ownerId:text('owner_id').primaryKey(),subject:text('subject').notNull()},t=>[uniqueIndex('owners_subject').on(t.subject)]);
const scope=()=>({ownerId:text('owner_id').notNull(),space:text('space').notNull()});
export const workspacesV2=sqliteTable('workspaces_v2',{...scope(),revision:integer('revision').notNull().default(0),schemaVersion:integer('schema_version').notNull().default(2)},t=>[primaryKey({columns:[t.ownerId,t.space]})]);
export const tasks=sqliteTable('tasks',{...scope(),taskId:text('task_id').notNull(),version:integer('version').notNull(),flow:text('flow').notNull(),status:text('status').notNull(),deletedAt:text('deleted_at'),updatedAt:text('updated_at').notNull(),payload:text('payload').notNull(),ordinal:integer('ordinal').notNull()},t=>[primaryKey({columns:[t.ownerId,t.space,t.taskId]})]);
export const dailyCompletions=sqliteTable('daily_completions',{...scope(),taskId:text('task_id').notNull(),date:text('beijing_date').notNull(),completed:integer('completed').notNull(),version:integer('version').notNull(),ordinal:integer('ordinal').notNull()},t=>[primaryKey({columns:[t.ownerId,t.space,t.taskId,t.date]})]);
export const workspaceSettings=sqliteTable('workspace_settings',{...scope(),version:integer('version').notNull(),payload:text('payload').notNull()},t=>[primaryKey({columns:[t.ownerId,t.space]})]);
export const receipts=sqliteTable('mutation_receipts',{...scope(),operationId:text('operation_id').notNull(),clientId:text('client_id').notNull(),requestHash:text('request_hash').notNull(),resultJson:text('result_json').notNull().default('{}'),resultSeq:integer('result_seq').notNull().default(0),createdAt:text('created_at').notNull()},t=>[primaryKey({columns:[t.ownerId,t.space,t.operationId]})]);
export const changeLog=sqliteTable('change_log',{...scope(),seq:integer('seq').notNull(),operationId:text('operation_id').notNull(),kind:text('kind').notNull(),dtoJson:text('dto_json').notNull(),createdAt:text('created_at').notNull()},t=>[primaryKey({columns:[t.ownerId,t.space,t.seq]})]);
export const migrationRuns=sqliteTable('migration_runs',{...scope(),runId:text('run_id').notNull(),kind:text('kind').notNull(),sourceHash:text('source_hash').notNull(),result:text('result').notNull(),createdAt:text('created_at').notNull()},t=>[primaryKey({columns:[t.ownerId,t.space,t.runId]})]);
export const snapshotsV2=sqliteTable('snapshots_v2',{...scope(),id:text('id').notNull(),payload:text('payload').notNull(),createdAt:text('created_at').notNull()},t=>[primaryKey({columns:[t.ownerId,t.space,t.id]}),index('snapshot_lookup').on(t.ownerId,t.space,t.createdAt)]);
export const backupRuns=sqliteTable('backup_runs',{...scope(),id:text('id').notNull(),status:text('status').notNull(),bytes:integer('bytes').notNull().default(0),sha256:text('sha256'),error:text('error'),createdAt:text('created_at').notNull()},t=>[primaryKey({columns:[t.ownerId,t.space,t.id]})]);
export const authSessions=sqliteTable('auth_sessions',{tokenHash:text('token_hash').primaryKey(),credentialTag:text('credential_tag').notNull(),expiresAt:integer('expires_at').notNull(),revoked:integer('revoked').notNull().default(0),createdAt:integer('created_at').notNull()});
export const authAttempts=sqliteTable('auth_attempts',{bucket:text('bucket').primaryKey(),attempts:integer('attempts').notNull(),expiresAt:integer('expires_at').notNull()});

export const coordinationState=sqliteTable('coordination_state',{...scope(),queueVersion:integer('queue_version').notNull().default(0),ready:integer('ready').notNull().default(0),coverage:text('coverage').notNull()},t=>[primaryKey({columns:[t.ownerId,t.space]})]);
export const taskEvents=sqliteTable('task_events',{...scope(),eventId:text('event_id').notNull(),taskId:text('task_id').notNull(),kind:text('kind').notNull(),date:text('date').notNull(),payload:text('payload').notNull()},t=>[primaryKey({columns:[t.ownerId,t.space,t.eventId]}),index('task_events_date').on(t.ownerId,t.space,t.date)]);
