'use client';
import {useEffect,useRef,useState,useMemo,useCallback,type CSSProperties} from 'react';
import {TimeAiPanel} from '@/components/time-ai-panel';
import {BoardSwitch} from '@/components/board-switch';
import {TimeImportPanel} from '@/components/time-import-panel';
import {TimeClient,timeRequest,shanghaiDate,dayStart,localClock,atLocal,clippedMinutes,type TimeInterval,type TimeMutation,type TimeCategory} from '@/lib/time-client';
import './time.css';
import {TimeMatrix} from '@/components/time-matrix';
import {TimeAnalytics} from '@/components/time-analytics';
import {TIME_SLOT_MS,TIME_SLOTS_PER_DAY,summarizeTimeSlot,timeSlotClock} from '@/lib/time-grid';
type Candidate={start:string;end:string;categoryId:string;note:string;sourceKey:string;kind:'plan'|'actual';estimated?:boolean};
type Draft={id?:string;plan?:boolean;date:string;endDate:string;start:string;end:string;categoryId:string;note:string};
const emptyDraft=(day=shanghaiDate()):Draft=>({date:day,endDate:day,start:'14:10',end:'15:35',categoryId:'study',note:''});
const duration=(m:number)=>{const rounded=Math.max(0,Math.round(m));return rounded>=60?`${Math.floor(rounded/60)}h ${rounded%60}m`:`${rounded}m`;};
const percent=(a:number,b:number)=>b>0?(100*a/b).toFixed(1)+'%':'—';
const offsetDay=(day:string,n:number)=>shanghaiDate(dayStart(day)+n*86400000);
function safeTime(day:string,time:string){try{return atLocal(day,time);}catch{return '';}}
export default function TimePage(){
 const [space,setSpace]=useState<'personal'|'demo'>('personal'),[ready,setReady]=useState(false),[,render]=useState(0),[anchor,setAnchor]=useState(shanghaiDate()),[selected,setSelected]=useState(shanghaiDate()),[now,setNow]=useState(Date.now());
 const [editor,setEditor]=useState(false),[draft,setDraft]=useState<Draft>(emptyDraft()),[error,setError]=useState(''),[importing,setImporting]=useState(false),[candidates,setCandidates]=useState<Candidate[]>([]),[source,setSource]=useState(''),[settings,setSettings]=useState(false),[highlight,setHighlight]=useState<string|null>(null),[replace,setReplace]=useState(false),[restore,setRestore]=useState<unknown>(null),[garmin,setGarmin]=useState<Record<string,unknown>|null>(null),[token,setToken]=useState('');
 const [theme,setTheme]=useState<'dark'|'light'>('dark'),[inspector,setInspector]=useState(false);
 const inspectDay=useCallback((day:string)=>{setSelected(day);setInspector(true);},[]);
 const client=useRef<TimeClient|null>(null),drag=useRef<number|null>(null),timerCategory=useRef<HTMLSelectElement>(null);
 useEffect(()=>{if(!editor&&!importing&&!settings)return;const prior=document.activeElement as HTMLElement|null;const dialog=document.querySelector<HTMLElement>('.time-dialog');const focusables=()=>Array.from(dialog?.querySelectorAll<HTMLElement>('button:not(:disabled),input:not(:disabled),select:not(:disabled),textarea:not(:disabled),a[href],summary')||[]).filter(x=>x.offsetParent!==null);focusables()[0]?.focus();const key=(event:KeyboardEvent)=>{if(event.key==='Escape'){setEditor(false);setImporting(false);setSettings(false);}if(event.key==='Tab'){const list=focusables(),first=list[0],last=list[list.length-1];if(event.shiftKey&&document.activeElement===first){event.preventDefault();last?.focus();}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first?.focus();}}};document.addEventListener('keydown',key);return()=>{document.removeEventListener('keydown',key);prior?.focus();};},[editor,importing,settings]);
 useEffect(()=>{setTheme(localStorage.getItem('qs-time-theme')==='light'?'light':'dark');setAnchor(shanghaiDate());setSelected(shanghaiDate());setNow(Date.now());if(localStorage.getItem('qs-selected-space')==='demo')setSpace('demo');setReady(true);},[]);
 useEffect(()=>{if(!ready)return;const c=new TimeClient(space,()=>render(n=>n+1));client.current=c;void c.start().then(async()=>{if(!c.stopped){const d=await c.draft<Draft>();if(d)setDraft(d);}});const tick=setInterval(()=>{setNow(Date.now());void c.sync();},30000),online=()=>void c.sync();window.addEventListener('online',online);if('serviceWorker'in navigator)void navigator.serviceWorker.register('/sw.js').catch(()=>{});return()=>{c.stopped=true;clearInterval(tick);window.removeEventListener('online',online);};},[space,ready]);
 const c=client.current,data=c?.data;
 const categories=useMemo(()=>(data?.categories||[]).filter(x=>x.id!=='unrecorded'),[data?.categories]),active=useMemo(()=>categories.filter(x=>x.active!==false),[categories]),rows=useMemo(()=>data?.intervals||[],[data?.intervals]),allPlans=useMemo(()=>data?.plans||[],[data?.plans]),plans=useMemo(()=>allPlans.filter(x=>!['cancelled','confirmed'].includes(x.status)),[allPlans]);
 const first=offsetDay(anchor,-54),count=60,last=offsetDay(anchor,5),today=shanghaiDate(now);
 const start=dayStart(first),end=start+count*86400000,elapsed=Math.max(0,(Math.min(end,now)-start)/60000),recorded=clippedMinutes(rows,start,end,now);
 const anchorOffset=Math.round((dayStart(anchor)-dayStart(today))/86400000),earliest=rows.reduce((day,r)=>r.start.slice(0,10)<day?r.start.slice(0,10):day,offsetDay(today,-365)),browseMin=Math.min(-365,Math.floor((dayStart(earliest)-dayStart(today))/86400000),anchorOffset),browseMax=Math.max(0,anchorOffset);
 const getCat=(id:string)=>categories.find(x=>x.id===id),dayRows=rows.filter(r=>Date.parse(r.start)<dayStart(selected)+86400000&&Date.parse(r.end)>dayStart(selected)).sort((a,b)=>a.start.localeCompare(b.start)),dayPlans=plans.filter(r=>Date.parse(r.start)<dayStart(selected)+86400000&&Date.parse(r.end)>dayStart(selected));
 const timer=(c?.pending||[]).filter(p=>p.state==='queued').reduce<{start:string;categoryId:string;note:string}|null>((prior,p)=>p.mutation.type==='timerStart'&&typeof p.mutation.start==='string'?{start:p.mutation.start,categoryId:String(p.mutation.categoryId),note:String(p.mutation.note||'')}:p.mutation.type==='timerStop'?null:prior,data?.timer||null);
 const overlap=rows.filter(r=>r.id!==draft.id&&Date.parse(r.start)<Date.parse(safeTime(draft.endDate,draft.end))&&Date.parse(r.end)>Date.parse(safeTime(draft.date,draft.start)));
 async function act(mutation:TimeMutation){setError('');try{await c?.enqueue(mutation);}catch(e){setError(e instanceof Error?e.message:'操作失败');}}
 function edit(row?:TimeInterval,plan=false){setReplace(false);setDraft(row?{id:row.id,plan,date:shanghaiDate(Date.parse(row.start)),endDate:shanghaiDate(Date.parse(row.end)),start:localClock(row.start),end:localClock(row.end),categoryId:row.categoryId,note:row.note||''}:emptyDraft(selected));setEditor(true);}
 function change(patch:Partial<Draft>){const d={...draft,...patch};setDraft(d);void c?.saveDraft(d);setReplace(false);}
 async function save(){const a=safeTime(draft.date,draft.start),b=safeTime(draft.endDate,draft.end);if(!a||!b||b<=a){setError('结束必须晚于开始；跨午夜请选择次日。');return;}if(!draft.plan&&Date.parse(b)>Date.now()){setError('实际记录不能包含未来，请通过课程计划录入未来安排。');return;}if(!draft.plan&&overlap.length&&!replace){setError('请核对重叠影响并确认替换。');return;}if(draft.plan)await act({type:'upsertPlan',plan:{id:draft.id,start:a,end:b,categoryId:draft.categoryId,note:draft.note}});else await act({type:'upsert',interval:{id:draft.id||crypto.randomUUID(),start:a,end:b,categoryId:draft.categoryId,note:draft.note},replace});setEditor(false);}
 function selectRange(i:number){if(drag.current===null)return;const lo=Math.min(drag.current,i),hi=Math.max(drag.current,i)+1;setDraft({...emptyDraft(selected),start:timeSlotClock(lo),end:timeSlotClock(hi),endDate:hi===TIME_SLOTS_PER_DAY?offsetDay(selected,1):selected});setReplace(false);setEditor(true);drag.current=null;}
 function dot(day:string,i:number):CSSProperties{const slot=summarizeTimeSlot(rows,dayStart(day)+i*TIME_SLOT_MS,now,plans),hollow=slot.state==='planned'||slot.state==='future';return {backgroundColor:hollow?'transparent':slot.categoryId==='unrecorded'?'var(--time-unrecorded)':getCat(slot.categoryId||'')?.color||'var(--time-unrecorded)',border:slot.state==='planned'?'1px solid var(--time-plan)':slot.state==='future'?'1px solid var(--time-future)':'none',opacity:highlight&&slot.categoryId!==highlight?.2:1};}
 function detail(day:string,i:number){const a=dayStart(day)+i*TIME_SLOT_MS,b=a+TIME_SLOT_MS,slot=summarizeTimeSlot(rows,a,now,plans);const breakdown=slot.parts.map(p=>((p.categoryId==='unrecorded'?'未记录':getCat(p.categoryId)?.name)||p.categoryId)+' '+Number(p.minutes.toFixed(2))+'分钟').join('；');return day+' '+localClock(new Date(a).toISOString())+'—'+localClock(new Date(b).toISOString())+' · '+(slot.state==='future'?'未来':slot.state==='planned'?'待确认计划':breakdown);}
 function chooseTheme(value:'dark'|'light'){setTheme(value);localStorage.setItem('qs-time-theme',value);}
 function confirmPlans(items:TimeInterval[]){const eligible=items.filter(p=>Date.parse(p.end)<=Date.now());if(!eligible.length){setError('没有已经结束的待确认课程');return;}const affected=rows.filter(r=>eligible.some(p=>r.start<p.end&&r.end>p.start));if(affected.length&&!confirm(`课程与${affected.length}段实际记录重叠，确认替换重叠部分？`))return;void act({type:'confirmPlan',ids:eligible.map(p=>p.id),replace:!!affected.length});}
 function shift(n:number){setAnchor(offsetDay(anchor,n*7));}
 async function download(){try{const exported=await timeRequest('/api/time/export?space='+space),a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(exported,null,2)],{type:'application/json'}));a.download=`时间备份-${space}-${shanghaiDate()}.json`;a.click();URL.revokeObjectURL(a.href);}catch(e){setError(String(e));}}
 async function garminCall(path:string,method='GET'){try{const value=await timeRequest<Record<string,unknown>>('/api/time/garmin/'+path+(method==='GET'?'?space='+space:''),method==='GET'?undefined:{method,headers:{'Content-Type':'application/json'},body:JSON.stringify({space})});const {token:credential,...status}=value;setGarmin(status);if(typeof credential==='string')setToken(credential);}catch(e){setError(String(e));}}
 function renderDayDetail(){return <>
 <div className="time-section-head time-timeline-heading"><h3>{selected} / 日时间轴</h3><button onClick={()=>edit()}>补录当天</button></div><p className="time-help">拖选时间条补录；点击整段修改。键盘可聚焦时间条并按 Enter 选择10分钟。</p><div className="time-day-strip" role="group" aria-label="选择当天时间段">{Array.from({length:TIME_SLOTS_PER_DAY},(_,i)=><button key={i} style={dot(selected,i)} title={detail(selected,i)} aria-label={detail(selected,i)} onPointerDown={()=>{drag.current=i;}} onPointerUp={()=>selectRange(i)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();drag.current=i;selectRange(i);}}}/>)}</div><div className="time-strip-label"><span>00:00</span><span>06:00</span><span>12:00</span><span>18:00</span><span>24:00</span></div>
 <div className="time-records">{dayRows.length===0&&<p className="time-empty">这一天还没有实际记录。可以补录、开始计时，或确认课程计划。</p>}{dayRows.map(row=><button className="time-record" key={row.id} onClick={()=>edit(row)}><i style={{background:getCat(row.categoryId)?.color}}/><time>{localClock(row.start)} — {localClock(row.end)}{shanghaiDate(Date.parse(row.start))!==shanghaiDate(Date.parse(row.end))?' +跨日':''}</time><b>{getCat(row.categoryId)?.name||row.categoryId}</b><span>{row.note}{row.estimated?' · 设备估计':''}</span><em>{duration((Date.parse(row.end)-Date.parse(row.start))/60000)}</em></button>)}</div>
 {!!dayPlans.length&&<section className="time-plans"><div className="time-section-head"><h3>待确认课程 / {dayPlans.length}</h3><button onClick={()=>confirmPlans(dayPlans)}>确认今天已上的课</button></div>{dayPlans.map(p=><div key={p.id}><time>{localClock(p.start)} — {localClock(p.end)}</time><span>{p.note}</span><button onClick={()=>edit(p,true)}>调课 / 修改</button><button disabled={Date.parse(p.end)>now} onClick={()=>confirmPlans([p])}>上过</button><button onClick={()=>void act({type:'cancelPlan',id:p.id})}>取消 / 缺席</button></div>)}</section>}
 </>;}
 if(!ready)return <main className="time-app" data-theme={theme}><p role="status">正在加载时间看板…</p></main>;
 return <main className="time-app" data-theme={theme}>
 <header className="time-header"><div><div className="time-kicker">QIUSHAN / PERSONAL WORKSPACE</div><h1>时间<BoardSwitch current="time" space={space}/></h1></div><div className="time-header-actions"><div className="time-theme-switch" role="group" aria-label="时间看板主题"><button aria-pressed={theme==='dark'} onClick={()=>chooseTheme('dark')}>深色</button><button aria-pressed={theme==='light'} onClick={()=>chooseTheme('light')}>浅色</button></div><span role="status">{c?.message||'正在连接'}</span><select aria-label="时间空间" value={space} onChange={e=>{const value=e.target.value as 'personal'|'demo';localStorage.setItem('qs-selected-space',value);setSpace(value);setEditor(false);setCandidates([]);setRestore(null);setToken('');}}><option value="personal">个人</option><option value="demo">演示</option></select><button onClick={()=>{setSettings(true);void garminCall('status');}}>设置 / 备份</button></div></header>
 {c?.blocked?<section className="time-notice"><h2>重新登录以继续</h2><p>{c.message}</p><a href="/login?next=/time">登录工作台</a></section>:<>
 <section className="time-intro"><div><p className="time-kicker">把时间看清楚，不给生活打分</p><h2>{first.slice(5).replace('-',' / ')} — {last.slice(5).replace('-',' / ')}</h2><div className="time-range"><button aria-label="向前浏览7天" onClick={()=>shift(-1)}>←</button><input type="date" aria-label="查看日期" value={anchor} onChange={e=>{if(e.target.value){setAnchor(e.target.value);setSelected(e.target.value);}}}/><button aria-label="向后浏览7天" onClick={()=>shift(1)}>→</button><button onClick={()=>{setAnchor(today);setSelected(today);}}>回到今天</button></div></div><div className="time-metrics"><div><strong>{percent(recorded,elapsed)}</strong><span>覆盖率</span></div><div><strong>{(recorded/60).toFixed(1)}<small> h</small></strong><span>已记录</span></div><div><strong>{Math.max(0,(elapsed-recorded)/60).toFixed(1)}<small> h</small></strong><span>未记录</span></div></div></section>
 <div className="time-tools"><button className="time-primary" disabled={!data} onClick={()=>edit()}>＋ 补录时间</button><button disabled={!data} onClick={()=>setImporting(true)}>文字 / 课表 / 文件导入</button><select aria-label="计时活动" ref={timerCategory}>{active.map(cat=><option key={cat.id} value={cat.id}>{cat.name}</option>)}</select>{timer?<button onClick={()=>{const long=Date.now()-Date.parse(timer!.start)>16*3600000;if(long&&!confirm('计时超过16小时，请核对开始时间。确定保存？'))return;const affected=rows.filter(r=>Date.parse(r.end)>Date.parse(timer!.start)&&Date.parse(r.start)<Date.now());if(affected.length&&!confirm(`计时与${affected.length}段重叠，确认替换重叠部分？`))return;void act({type:'timerStop',end:new Date().toISOString(),replace:!!affected.length,confirmedLong:long});}}>■ 结束 · {duration((now-Date.parse(timer.start))/60000)}</button>:<button disabled={!data||!!c?.pending.length} onClick={()=>void act({type:'timerStart',start:new Date().toISOString(),categoryId:timerCategory.current?.value||'study',note:''})}>● 开始计时</button>}<button onClick={()=>void c?.sync()}>同步</button>{plans.length>0?<button className="time-plan-shortcut" onClick={()=>{const plan=plans.find(p=>Date.parse(p.end)<=now)||plans[0];inspectDay(shanghaiDate(Date.parse(plan.start)));}}>课程计划 {plans.length} 节 · {plans.filter(p=>Date.parse(p.end)<=now).length} 节待确认</button>:<span>Asia/Shanghai · 周一周首</span>}</div>
 {error&&<div className="time-notice" role="alert">{error}<button onClick={()=>setError('')}>关闭</button></div>}
 {!!c?.pending.length&&<details className="time-notice time-sync-notice"><summary>本机待同步 / 待核对 · {c.pending.length} 条（展开处理）</summary><p>{c.message}</p><button onClick={()=>void c.sync()}>立即重试同步</button>{c.pending.map(p=><div key={p.operationId}><span>{p.mutation.type==='setAttendance'?'课程出勤标注':p.mutation.type} · {p.state==='queued'?'等待同步（网络恢复后自动重试）':p.error}</span>{p.state!=='queued'&&<><button onClick={()=>{if(confirm('已读取最新时间记录。确认在最新版本重新提交？'))void c.resolve(p.operationId,true).catch(e=>setError(String(e)));}}>核对后重试</button><button onClick={()=>void c.resolve(p.operationId,false).catch(e=>setError(String(e)))}>保留归档，取消提交</button></>}</div>)}</details>}
 <section className="time-workspace"><div className="time-main-panel time-mode-history"><div className="time-section-head"><h3>60 天时间点阵</h3><span>10分钟 / 格 · 主类别着色 · 空心为计划 / 未来</span></div>
 <TimeMatrix rows={rows} plans={plans} categories={categories} first={first} count={count} now={now} selected={selected} onSelect={inspectDay}/>
 <div className="time-browse"><div><span>{first} — {last}</span><span>拖动浏览更早日期 · 点击日期查看明细</span></div><input type="range" aria-label="浏览点阵日期" aria-valuetext={first+' 至 '+last} min={browseMin} max={browseMax} step={1} value={anchorOffset} onChange={e=>setAnchor(offsetDay(today,Number(e.target.value)))}/><div><span>更早</span><span>{anchor===today?'今天 + 未来 5 天':'日历定位：'+anchor}</span></div></div>
 </div><aside className="time-sidebar">{inspector?<div className="time-inspector"><div className="time-section-head"><h3>当天明细</h3><button onClick={()=>setInspector(false)}>返回统计</button></div><div className="time-inspector-body">{renderDayDetail()}</div></div>:<TimeAnalytics rows={rows} plans={allPlans} categories={categories} now={now} act={act} onSettings={()=>setSettings(true)}/>}</aside></section>
 </>}
 {editor&&<div className="time-overlay"><section role="dialog" aria-modal="true" aria-labelledby="time-edit-title" className="time-dialog"><div className="time-section-head"><h2 id="time-edit-title">{draft.plan?'调整课程计划':draft.id?'修改整段':'补录时间'}</h2><button onClick={()=>setEditor(false)}>关闭</button></div><div className="time-form"><label>开始日期<input type="date" value={draft.date} onChange={e=>change({date:e.target.value})}/></label><label>开始时间<input type="time" value={draft.start} onChange={e=>change({start:e.target.value})}/></label><label>结束日期<input type="date" value={draft.endDate} onChange={e=>change({endDate:e.target.value})}/></label><label>结束时间<input type="time" value={draft.end} onChange={e=>change({end:e.target.value})}/></label><label>活动<select aria-label="活动" value={draft.categoryId} onChange={e=>change({categoryId:e.target.value})}>{categories.filter(x=>x.active!==false||x.id===draft.categoryId).map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>备注<input value={draft.note} onChange={e=>change({note:e.target.value})}/></label></div><div className="time-templates"><span>常用模板</span>{[{label:'专注 85分钟',start:'14:10',end:'15:35',categoryId:'study'},{label:'午睡',start:'12:30',end:'13:00',categoryId:'sleep'},{label:'用餐',start:'18:00',end:'18:30',categoryId:'meal'}].map(t=><button key={t.label} onClick={()=>change({...t,endDate:draft.date})}>{t.label}</button>)}</div>{!draft.plan&&overlap.length>0&&<div className="time-notice"><b>将影响 {overlap.length} 段</b>{overlap.map(r=><p key={r.id}>{shanghaiDate(Date.parse(r.start))} {localClock(r.start)}—{localClock(r.end)} {getCat(r.categoryId)?.name}</p>)}<label><input type="checkbox" checked={replace} onChange={e=>setReplace(e.target.checked)}/>确认替换重叠部分，原记录两端保留</label></div>}{error&&<p role="alert">{error}</p>}<div className="time-dialog-actions"><button className="time-primary" onClick={()=>void save()}>保存准确时间段</button>{draft.id&&!draft.plan&&<button onClick={()=>{void act({type:'delete',id:draft.id});setEditor(false);}}>删除此段（可撤销）</button>}</div><p className="time-help">输入草稿只保存在本机；顶部“已同步”才代表服务端已接收。</p></section></div>}
 {importing&&<div className="time-overlay"><section className="time-dialog wide" role="dialog" aria-modal="true" aria-label="导入预览"><div className="time-section-head"><h2>识别与导入</h2><button onClick={()=>setImporting(false)}>关闭</button></div><TimeAiPanel/><TimeImportPanel onPreview={(items:Candidate[],from:string)=>{setCandidates(items);setSource(from);}}/>{!!candidates.length&&<section><h3>最终预览 · {candidates.length} 段</h3><p>来源 {source}。计划与实际分开保存；重复来源不覆盖人工修正。</p><div className="time-preview-list">{candidates.map((x,i)=><p key={i}>{x.kind==='plan'?'计划':'实际'} · {shanghaiDate(Date.parse(x.start))} {localClock(x.start)}—{localClock(x.end)} · {x.note}</p>)}</div><button className="time-primary" onClick={()=>{void act({type:'import',items:candidates,source});setCandidates([]);setImporting(false);}}>确认导入这些区间</button></section>}</section></div>}
 {settings&&<div className="time-overlay"><section className="time-dialog wide" role="dialog" aria-modal="true" aria-label="时间设置"><div className="time-section-head"><h2>时间设置</h2><button onClick={()=>setSettings(false)}>关闭</button></div><h3>活动分类</h3><p>停用后保留历史；颜色只用来区分活动。</p>{categories.map(cat=><CategoryEdit key={cat.id+cat.name+cat.color+cat.active} category={cat} save={value=>void act({type:'category',category:value})}/>)}<h3>独立备份与恢复</h3><button onClick={()=>void download()}>下载时间备份</button><label className="time-file">选择时间备份<input type="file" accept=".json" onChange={async e=>{const file=e.target.files?.[0];if(file)try{setRestore(JSON.parse(await file.text()));}catch{setError('备份不是有效JSON');}}}/></label>{restore!==null&&<div className="time-notice"><p>恢复只替换当前空间时间数据，服务端验证哈希和版本；工作流数据保持独立。</p><button onClick={()=>{if(confirm('确认恢复此时间备份？当前时间数据将被替换。'))void act({type:'restore',backup:restore});setRestore(null);}}>确认恢复</button><button onClick={()=>setRestore(null)}>取消</button></div>}<h3>导入回执</h3>{(data?.imports||[]).slice(-5).reverse().map(x=><p key={x.id}>{x.source} · 接收 {x.accepted||0} 段 · 跳过 {x.skipped||0} 段（重复或人工保护）</p>)}<h3>修正与撤销</h3>{(data?.corrections||[]).slice(-8).reverse().map(x=><div className="time-correction" key={x.id}><span>{x.kind||'时间修正'} · {x.createdAt||x.id.slice(0,8)}</span><button disabled={x.undone} onClick={()=>void act({type:'undo',correctionId:x.id})}>{x.undone?'已撤销':'撤销'}</button></div>)}<h3>Garmin 中国区 · 本机同步</h3><p>首次需在本机同步器完成登录和 MFA。浏览器不收集 Garmin 密码。电脑离线时，下次启动补同步。</p><p>连接：{garmin?.status==='active'?'已连接':garmin?.status==='queued'?'已排队，等待电脑同步':garmin?.status==='revoked'?'已撤销':'尚未连接或未获取状态'}<br/>上次成功同步：{typeof garmin?.lastSyncAt==='string'?new Date(garmin.lastSyncAt).toLocaleString('zh-CN',{timeZone:'Asia/Shanghai'}):'尚无成功记录'}</p><button onClick={()=>void garminCall('request','POST')}>立即同步 / 排队</button><button onClick={()=>void garminCall('token','POST')}>创建只允许时间导入的凭证</button><button onClick={()=>void garminCall('revoke','POST')}>撤销连接</button>{token&&<label>仅显示本次，请保存到本机同步器<input type="password" readOnly value={token}/><button onClick={()=>void navigator.clipboard.writeText(token)}>复制凭证</button></label>}<h3>云端 AI</h3><p>默认关闭。核心录入、统计与本地识别不需要云端 AI；当前未配置，不发送图片或文字。</p></section></div>}
 <footer className="time-footer">TIME, WITH CONTEXT. <span>北京时间 · 准确区间记录</span></footer></main>;
}
function CategoryEdit({category,save}:{category:TimeCategory;save:(category:TimeCategory)=>void}){const [value,setValue]=useState(category);return <div className="time-category-edit"><input aria-label={category.name+'名称'} value={value.name} onChange={e=>setValue({...value,name:e.target.value})}/><input aria-label={category.name+'颜色'} type="color" value={value.color} onChange={e=>setValue({...value,color:e.target.value})}/><label><input type="checkbox" checked={value.active!==false} onChange={e=>setValue({...value,active:e.target.checked})}/>启用</label><button onClick={()=>save(value)}>保存</button></div>;}
